// Code generated by logcopter-gen; DO NOT EDIT.

package exportmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.pkg.jsdoc.exportmd")
