package generator

import (
	"path/filepath"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

// Generate emits one Goja protobuf-builder companion Go file for every proto
// file selected by protoc.
func Generate(plugin *protogen.Plugin, opts Options) error {
	if opts.BuilderSuffix == "" {
		opts.BuilderSuffix = DefaultOptions().BuilderSuffix
	}
	if opts.MessageRefName == "" {
		opts.MessageRefName = DefaultOptions().MessageRefName
	}
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		generateFile(plugin, file, opts)
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_goja.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-goja-builder. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	moduleName := opts.ModuleName
	if moduleName == "" {
		moduleName = string(file.Desc.Package())
	}
	ident := fileIdentifier(file.Desc.Path())
	g.P("// GojaBuilderFile", ident, "ModuleName returns the JavaScript module name for this generated protobuf builder companion file.")
	g.P("func GojaBuilderFile", ident, "ModuleName() string {")
	g.P("\treturn ", quoted(moduleName))
	g.P("}")
	g.P()
	g.P("// GojaBuilderFile", ident, "MessageTypes returns the full protobuf message names exported by this generated builder companion file.")
	g.P("func GojaBuilderFile", ident, "MessageTypes() []string {")
	g.P("\treturn []string{")
	for _, msg := range file.Messages {
		emitMessageName(g, msg)
	}
	g.P("\t}")
	g.P("}")
}

func emitMessageName(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("\t\t", quoted(string(msg.Desc.FullName())), ",")
	for _, nested := range msg.Messages {
		emitMessageName(g, nested)
	}
}

func fileIdentifier(path string) string {
	base := filepath.Base(path)
	var b strings.Builder
	capitalizeNext := true
	for _, r := range base {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if capitalizeNext {
				r = unicode.ToUpper(r)
			}
			b.WriteRune(r)
			capitalizeNext = false
			continue
		}
		capitalizeNext = true
	}
	if b.Len() == 0 {
		return "Proto"
	}
	return b.String()
}

func quoted(s string) string {
	return "\"" + strings.ReplaceAll(s, "\"", "\\\"") + "\""
}
