package generator

import (
	"path/filepath"
	"strconv"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

var (
	errorsNewIdent                       = protogen.GoIdent{GoName: "New", GoImportPath: "errors"}
	gojaFunctionCallIdent                = protogen.GoIdent{GoName: "FunctionCall", GoImportPath: "github.com/dop251/goja"}
	gojaObjectIdent                      = protogen.GoIdent{GoName: "Object", GoImportPath: "github.com/dop251/goja"}
	gojaRuntimeIdent                     = protogen.GoIdent{GoName: "Runtime", GoImportPath: "github.com/dop251/goja"}
	gojaUndefinedIdent                   = protogen.GoIdent{GoName: "Undefined", GoImportPath: "github.com/dop251/goja"}
	gojaValueIdent                       = protogen.GoIdent{GoName: "Value", GoImportPath: "github.com/dop251/goja"}
	modulesNativeModuleIdent             = protogen.GoIdent{GoName: "NativeModule", GoImportPath: "github.com/go-go-golems/go-go-goja/modules"}
	protoMessageIdent                    = protogen.GoIdent{GoName: "Message", GoImportPath: "google.golang.org/protobuf/proto"}
	protogojaAttachBuilderRefIdent       = protogen.GoIdent{GoName: "AttachBuilderRef", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaAttachMessagePrototypeIdent = protogen.GoIdent{GoName: "AttachMessagePrototype", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaBuilderRefIdent             = protogen.GoIdent{GoName: "BuilderRef", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaIsMessageValueOfIdent       = protogen.GoIdent{GoName: "IsMessageValueOf", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaMessageFromValueIdent       = protogen.GoIdent{GoName: "MessageFromValue", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaNewBuilderIdent             = protogen.GoIdent{GoName: "NewBuilder", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	protogojaToValueIdent                = protogen.GoIdent{GoName: "ToValue", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/protogoja"}
	requireModuleLoaderIdent             = protogen.GoIdent{GoName: "ModuleLoader", GoImportPath: "github.com/dop251/goja_nodejs/require"}
	requireRegistryIdent                 = protogen.GoIdent{GoName: "Registry", GoImportPath: "github.com/dop251/goja_nodejs/require"}
	tsgenSpecModuleIdent                 = protogen.GoIdent{GoName: "Module", GoImportPath: "github.com/go-go-golems/go-go-goja/pkg/tsgen/spec"}
)

// Generate emits one Goja protobuf-builder companion Go file for every proto
// file selected by protoc.
func Generate(plugin *protogen.Plugin, opts Options) error {
	if opts.BuilderSuffix == "" {
		opts.BuilderSuffix = DefaultOptions().BuilderSuffix
	}
	if opts.MessageRefName == "" {
		opts.MessageRefName = DefaultOptions().MessageRefName
	}
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		generateFile(plugin, file, opts)
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File, opts Options) {
	filename := file.GeneratedFilenamePrefix + "_goja.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-goja-builder. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	moduleName := opts.ModuleName
	if moduleName == "" {
		moduleName = string(file.Desc.Package())
	}
	ident := fileIdentifier(file.Desc.Path())
	g.P("// GojaBuilderFile", ident, "ModuleName returns the JavaScript module name for this generated protobuf builder companion file.")
	g.P("func GojaBuilderFile", ident, "ModuleName() string {")
	g.P("\treturn ", quoted(moduleName))
	g.P("}")
	g.P()
	g.P("// GojaBuilderFile", ident, "MessageTypes returns the full protobuf message names exported by this generated builder companion file.")
	g.P("func GojaBuilderFile", ident, "MessageTypes() []string {")
	g.P("\treturn []string{")
	for _, msg := range file.Messages {
		emitMessageName(g, msg)
	}
	g.P("\t}")
	g.P("}")
	g.P()
	g.P("// GojaBuilderFile", ident, "TypeScriptModule returns the TypeScript declaration descriptor for this generated protobuf builder companion file.")
	g.P("func GojaBuilderFile", ident, "TypeScriptModule(moduleName string) *", g.QualifiedGoIdent(tsgenSpecModuleIdent), " {")
	g.P("\tif moduleName == \"\" {")
	g.P("\t\tmoduleName = GojaBuilderFile", ident, "ModuleName()")
	g.P("\t}")
	g.P("\treturn &", g.QualifiedGoIdent(tsgenSpecModuleIdent), "{")
	g.P("\t\tName: moduleName,")
	g.P("\t\tRawDTS: []string{")
	for _, line := range rawDTSLines(file) {
		g.P("\t\t\t", quoted(line), ",")
	}
	g.P("\t\t},")
	g.P("\t}")
	g.P("}")
	emitHostIntegration(g, file, ident)
	for _, enum := range file.Enums {
		emitEnumAPI(g, enum)
	}
	for _, msg := range file.Messages {
		emitMessageAPI(g, msg)
	}
}

func rawDTSLines(file *protogen.File) []string {
	lines := []string{
		"export interface ProtoMessage<TTypeName extends string = string> {",
		"  readonly typeName: TTypeName;",
		"  toJSON(): unknown;",
		"  clone(): ProtoMessage<TTypeName>;",
		"  equals(other: unknown): boolean;",
		"}",
		"export interface MessageNamespace<TMessage, TBuilder> {",
		"  readonly typeName: string;",
		"  builder(): TBuilder;",
		"  from(value: TMessage): TMessage;",
		"  is(value: unknown): value is TMessage;",
		"  clone(value: TMessage): TMessage;",
		"}",
	}
	for _, enum := range file.Enums {
		appendEnumDTS(&lines, enum)
	}
	for _, msg := range file.Messages {
		appendMessageDTS(&lines, msg)
	}
	return lines
}

func appendEnumDTS(lines *[]string, enum *protogen.Enum) {
	name := enum.GoIdent.GoName
	values := make([]string, 0, len(enum.Values))
	*lines = append(*lines, "export const "+name+": {")
	*lines = append(*lines, "  readonly typeName: "+quoted(string(enum.Desc.FullName()))+";")
	for _, value := range enum.Values {
		literal := strconv.FormatInt(int64(value.Desc.Number()), 10)
		values = append(values, literal)
		*lines = append(*lines, "  readonly "+string(value.Desc.Name())+": "+literal+";")
	}
	*lines = append(*lines, "};")
	if len(values) == 0 {
		values = append(values, "number")
	}
	*lines = append(*lines, "export type "+name+"Value = "+strings.Join(values, " | ")+";")
}

func appendMessageDTS(lines *[]string, msg *protogen.Message) {
	name := msg.GoIdent.GoName
	builderName := name + "Builder"
	*lines = append(*lines, "export interface "+name+" extends ProtoMessage<"+quoted(string(msg.Desc.FullName()))+"> {}")
	*lines = append(*lines, "export interface "+builderName+" {")
	for _, field := range msg.Fields {
		methodName := methodNameForField(field)
		exportedMethodName := exportName(methodName)
		tsType := tsTypeForField(field)
		*lines = append(*lines, "  "+methodName+"(value: "+tsType+"): this;")
		if field.Desc.IsList() && !field.Desc.IsMap() {
			*lines = append(*lines, "  add"+exportedMethodName+"(value: "+tsTypeForKind(field.Desc)+"): this;")
		}
		if field.Desc.IsMap() {
			*lines = append(*lines, "  put"+exportedMethodName+"(key: "+tsTypeForKind(field.Desc.MapKey())+", value: "+tsTypeForKind(field.Desc.MapValue())+"): this;")
			*lines = append(*lines, "  delete"+exportedMethodName+"(key: "+tsTypeForKind(field.Desc.MapKey())+"): this;")
		}
		if field.Desc.HasPresence() {
			*lines = append(*lines, "  has"+exportedMethodName+"(): boolean;")
		}
		*lines = append(*lines, "  clear"+exportedMethodName+"(): this;")
	}
	for _, oneof := range realOneofs(msg) {
		methodName := exportName(lowerCamel(string(oneof.Desc.Name())))
		*lines = append(*lines, "  which"+methodName+"(): "+oneofSelectionType(oneof)+" | undefined;")
		*lines = append(*lines, "  clear"+methodName+"(): this;")
	}
	*lines = append(*lines, "  build(): "+name+";")
	*lines = append(*lines, "  clone(): "+builderName+";")
	*lines = append(*lines, "}")
	*lines = append(*lines, "export const "+name+": MessageNamespace<"+name+", "+builderName+">;")
	for _, enum := range msg.Enums {
		appendEnumDTS(lines, enum)
	}
	for _, nested := range msg.Messages {
		appendMessageDTS(lines, nested)
	}
}

func tsTypeForField(field *protogen.Field) string {
	if field.Desc.IsMap() {
		return "Record<string, " + tsTypeForKind(field.Desc.MapValue()) + ">"
	}
	typ := tsTypeForKind(field.Desc)
	if field.Desc.IsList() {
		return typ + "[]"
	}
	return typ
}

func tsTypeForKind(field protoreflect.FieldDescriptor) string {
	switch field.Kind() {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.EnumKind:
		return string(field.Enum().Name()) + "Value | keyof typeof " + string(field.Enum().Name())
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "number"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "number | string"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "Uint8Array | string"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return string(field.Message().Name())
	default:
		return "unknown"
	}
}

func emitMessageName(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("\t\t", quoted(string(msg.Desc.FullName())), ",")
	for _, nested := range msg.Messages {
		emitMessageName(g, nested)
	}
}

func emitHostIntegration(g *protogen.GeneratedFile, file *protogen.File, ident string) {
	moduleStructName := "gojaBuilderFile" + ident + "Module"
	g.P()
	g.P("// NewGojaBuilderFile", ident, "Loader returns a CommonJS module loader for this generated protobuf builder companion file.")
	g.P("func NewGojaBuilderFile", ident, "Loader(moduleName string) ", g.QualifiedGoIdent(requireModuleLoaderIdent), " {")
	g.P("\treturn func(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ", moduleObj *", g.QualifiedGoIdent(gojaObjectIdent), ") {")
	g.P("\t\texports := moduleObj.Get(\"exports\").ToObject(vm)")
	for _, enum := range allEnums(file) {
		name := enum.GoIdent.GoName
		g.P("\t\t", lowerFirst(name), ", err := New", name, "GojaEnum(vm)")
		g.P("\t\tif err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\tif err := exports.Set(", quoted(name), ", ", lowerFirst(name), "); err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
	}
	for _, msg := range allMessages(file) {
		name := msg.GoIdent.GoName
		g.P("\t\t", lowerFirst(name), ", err := New", name, "GojaNamespace(vm)")
		g.P("\t\tif err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\tif err := exports.Set(", quoted(name), ", ", lowerFirst(name), "); err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
	}
	g.P("\t}")
	g.P("}")
	g.P()
	g.P("// RegisterGojaBuilderFile", ident, "Module registers this generated protobuf builder module in a goja require registry.")
	g.P("func RegisterGojaBuilderFile", ident, "Module(reg *", g.QualifiedGoIdent(requireRegistryIdent), ", moduleName string) error {")
	g.P("\tif reg == nil {")
	g.P("\t\treturn ", g.QualifiedGoIdent(errorsNewIdent), "(\"protogoja: nil require registry\")")
	g.P("\t}")
	g.P("\tif moduleName == \"\" {")
	g.P("\t\tmoduleName = GojaBuilderFile", ident, "ModuleName()")
	g.P("\t}")
	g.P("\treg.RegisterNativeModule(moduleName, NewGojaBuilderFile", ident, "Loader(moduleName))")
	g.P("\treturn nil")
	g.P("}")
	g.P()
	g.P("// GojaBuilderFile", ident, "Module returns a modules.NativeModule wrapper for this generated protobuf builder module.")
	g.P("func GojaBuilderFile", ident, "Module(moduleName string) ", g.QualifiedGoIdent(modulesNativeModuleIdent), " {")
	g.P("\tif moduleName == \"\" {")
	g.P("\t\tmoduleName = GojaBuilderFile", ident, "ModuleName()")
	g.P("\t}")
	g.P("\treturn &", moduleStructName, "{name: moduleName}")
	g.P("}")
	g.P()
	g.P("type ", moduleStructName, " struct { name string }")
	g.P("func (m *", moduleStructName, ") Name() string { return m.name }")
	g.P("func (m *", moduleStructName, ") Doc() string { return \"Generated protobuf Goja builder module for ", file.Desc.Package(), "\" }")
	g.P("func (m *", moduleStructName, ") Loader(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ", moduleObj *", g.QualifiedGoIdent(gojaObjectIdent), ") { NewGojaBuilderFile", ident, "Loader(m.name)(vm, moduleObj) }")
	g.P("func (m *", moduleStructName, ") TypeScriptModule() *", g.QualifiedGoIdent(tsgenSpecModuleIdent), " { return GojaBuilderFile", ident, "TypeScriptModule(m.name) }")
	g.P()
	g.P("// RegisterGojaBuilderFile", ident, "MessageTypes calls register for every message type exported by this generated builder companion file.")
	g.P("func RegisterGojaBuilderFile", ident, "MessageTypes(register func(string, ", g.QualifiedGoIdent(protoMessageIdent), ") error) error {")
	g.P("\tif register == nil {")
	g.P("\t\treturn ", g.QualifiedGoIdent(errorsNewIdent), "(\"protogoja: nil message type register function\")")
	g.P("\t}")
	for _, msg := range allMessages(file) {
		g.P("\tif err := register(", quoted(string(msg.Desc.FullName())), ", &", g.QualifiedGoIdent(msg.GoIdent), "{}); err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
	}
	g.P("\treturn nil")
	g.P("}")
}

func allMessages(file *protogen.File) []*protogen.Message {
	var out []*protogen.Message
	var visit func(messages []*protogen.Message)
	visit = func(messages []*protogen.Message) {
		for _, msg := range messages {
			out = append(out, msg)
			visit(msg.Messages)
		}
	}
	visit(file.Messages)
	return out
}

func allEnums(file *protogen.File) []*protogen.Enum {
	var out []*protogen.Enum
	out = append(out, file.Enums...)
	var visit func(messages []*protogen.Message)
	visit = func(messages []*protogen.Message) {
		for _, msg := range messages {
			out = append(out, msg.Enums...)
			visit(msg.Messages)
		}
	}
	visit(file.Messages)
	return out
}

func emitEnumAPI(g *protogen.GeneratedFile, enum *protogen.Enum) {
	name := enum.GoIdent.GoName
	g.P()
	g.P("// New", name, "GojaEnum returns the JavaScript enum export object for ", enum.Desc.FullName(), ".")
	g.P("func New", name, "GojaEnum(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ") (*", g.QualifiedGoIdent(gojaObjectIdent), ", error) {")
	g.P("\tif vm == nil {")
	g.P("\t\treturn nil, ", g.QualifiedGoIdent(errorsNewIdent), "(\"protogoja: nil runtime\")")
	g.P("\t}")
	g.P("\tobj := vm.NewObject()")
	g.P("\tif err := obj.Set(\"typeName\", ", quoted(string(enum.Desc.FullName())), "); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	for _, value := range enum.Values {
		g.P("\tif err := obj.Set(", quoted(string(value.Desc.Name())), ", ", int32(value.Desc.Number()), "); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
	}
	g.P("\treturn obj, nil")
	g.P("}")
}

func emitMessageAPI(g *protogen.GeneratedFile, msg *protogen.Message) {
	name := msg.GoIdent.GoName
	typeExpr := "&" + g.QualifiedGoIdent(msg.GoIdent) + "{}"
	g.P()
	g.P("// New", name, "GojaNamespace returns the JavaScript namespace object for ", msg.Desc.FullName(), ".")
	g.P("func New", name, "GojaNamespace(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ") (*", g.QualifiedGoIdent(gojaObjectIdent), ", error) {")
	g.P("\tif vm == nil {")
	g.P("\t\treturn nil, ", g.QualifiedGoIdent(errorsNewIdent), "(\"protogoja: nil runtime\")")
	g.P("\t}")
	g.P("\tobj := vm.NewObject()")
	g.P("\tif err := ", g.QualifiedGoIdent(protogojaAttachMessagePrototypeIdent), "(vm, obj, &", g.QualifiedGoIdent(msg.GoIdent), "{}); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"typeName\", ", quoted(string(msg.Desc.FullName())), "); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"builder\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tbuilder, err := New", name, "GojaBuilder(vm)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn builder")
	g.P("\t}); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"from\", func(value ", g.QualifiedGoIdent(gojaValueIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tmsg, ok := ", g.QualifiedGoIdent(protogojaMessageFromValueIdent), "(value)")
	g.P("\t\tif !ok || msg.ProtoReflect().Descriptor().FullName() != (", typeExpr, ").ProtoReflect().Descriptor().FullName() {")
	g.P("\t\t\tpanic(vm.NewTypeError(\"value is not a ", msg.Desc.FullName(), " ProtoMessage\"))")
	g.P("\t\t}")
	g.P("\t\tout, err := ", g.QualifiedGoIdent(protogojaToValueIdent), "(vm, msg)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn out")
	g.P("\t}); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"is\", func(value ", g.QualifiedGoIdent(gojaValueIdent), ") bool {")
	g.P("\t\treturn ", g.QualifiedGoIdent(protogojaIsMessageValueOfIdent), "(value, (", typeExpr, ").ProtoReflect().Descriptor().FullName())")
	g.P("\t}); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"clone\", func(value ", g.QualifiedGoIdent(gojaValueIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tmsg, ok := ", g.QualifiedGoIdent(protogojaMessageFromValueIdent), "(value)")
	g.P("\t\tif !ok || msg.ProtoReflect().Descriptor().FullName() != (", typeExpr, ").ProtoReflect().Descriptor().FullName() {")
	g.P("\t\t\tpanic(vm.NewTypeError(\"value is not a ", msg.Desc.FullName(), " ProtoMessage\"))")
	g.P("\t\t}")
	g.P("\t\tout, err := ", g.QualifiedGoIdent(protogojaToValueIdent), "(vm, msg)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn out")
	g.P("\t}); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\treturn obj, nil")
	g.P("}")
	g.P()
	g.P("// New", name, "GojaBuilder returns a JavaScript fluent builder object for ", msg.Desc.FullName(), ".")
	g.P("func New", name, "GojaBuilder(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ") (*", g.QualifiedGoIdent(gojaObjectIdent), ", error) {")
	g.P("\tif vm == nil {")
	g.P("\t\treturn nil, ", g.QualifiedGoIdent(errorsNewIdent), "(\"protogoja: nil runtime\")")
	g.P("\t}")
	g.P("\tbuilder, err := ", g.QualifiedGoIdent(protogojaNewBuilderIdent), "(&", g.QualifiedGoIdent(msg.GoIdent), "{})")
	g.P("\tif err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tobj := vm.NewObject()")
	g.P("\tif err := ", g.QualifiedGoIdent(protogojaAttachBuilderRefIdent), "(vm, obj, builder); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\tif err := attach", name, "GojaBuilderMethods(vm, obj, builder); err != nil {")
	g.P("\t\treturn nil, err")
	g.P("\t}")
	g.P("\treturn obj, nil")
	g.P("}")
	g.P()
	g.P("func attach", name, "GojaBuilderMethods(vm *", g.QualifiedGoIdent(gojaRuntimeIdent), ", obj *", g.QualifiedGoIdent(gojaObjectIdent), ", builder *", g.QualifiedGoIdent(protogojaBuilderRefIdent), ") error {")
	g.P("\tif err := obj.Set(\"build\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tout, err := ", g.QualifiedGoIdent(protogojaToValueIdent), "(vm, builder.Build())")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn out")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"clone\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tcloned, err := builder.Clone()")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\tcloneObj := vm.NewObject()")
	g.P("\t\tif err := ", g.QualifiedGoIdent(protogojaAttachBuilderRefIdent), "(vm, cloneObj, cloned); err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\tif err := attach", name, "GojaBuilderMethods(vm, cloneObj, cloned); err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn cloneObj")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	for _, field := range msg.Fields {
		emitFieldMethods(g, msg, field)
	}
	for _, oneof := range realOneofs(msg) {
		emitOneofMethods(g, msg, oneof)
	}
	g.P("\treturn nil")
	g.P("}")
	for _, enum := range msg.Enums {
		emitEnumAPI(g, enum)
	}
	for _, nested := range msg.Messages {
		emitMessageAPI(g, nested)
	}
}

func emitFieldMethods(g *protogen.GeneratedFile, msg *protogen.Message, field *protogen.Field) {
	fieldName := string(field.Desc.Name())
	methodName := methodNameForField(field)
	exportedMethodName := exportName(methodName)
	clearMethodName := "clear" + exportedMethodName
	hasMethodName := "has" + exportedMethodName
	g.P("\tif err := obj.Set(\"", methodName, "\", func(call ", g.QualifiedGoIdent(gojaFunctionCallIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
	g.P("\t\tif err := builder.Set(vm, field, call.Argument(0)); err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn obj")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	if field.Desc.IsList() && !field.Desc.IsMap() {
		addMethodName := "add" + exportedMethodName
		g.P("\tif err := obj.Set(\"", addMethodName, "\", func(call ", g.QualifiedGoIdent(gojaFunctionCallIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
		g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
		g.P("\t\tif err := builder.Add(vm, field, call.Argument(0)); err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\treturn obj")
		g.P("\t}); err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
	}
	if field.Desc.IsMap() {
		putMethodName := "put" + exportedMethodName
		deleteMethodName := "delete" + exportedMethodName
		g.P("\tif err := obj.Set(\"", putMethodName, "\", func(call ", g.QualifiedGoIdent(gojaFunctionCallIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
		g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
		g.P("\t\tif err := builder.Put(vm, field, call.Argument(0), call.Argument(1)); err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\treturn obj")
		g.P("\t}); err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
		g.P("\tif err := obj.Set(\"", deleteMethodName, "\", func(call ", g.QualifiedGoIdent(gojaFunctionCallIdent), ") ", g.QualifiedGoIdent(gojaValueIdent), " {")
		g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
		g.P("\t\tif err := builder.Delete(vm, field, call.Argument(0)); err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\treturn obj")
		g.P("\t}); err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
	}
	if field.Desc.HasPresence() {
		g.P("\tif err := obj.Set(\"", hasMethodName, "\", func() bool {")
		g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
		g.P("\t\thas, err := builder.Has(field)")
		g.P("\t\tif err != nil {")
		g.P("\t\t\tpanic(vm.NewGoError(err))")
		g.P("\t\t}")
		g.P("\t\treturn has")
		g.P("\t}); err != nil {")
		g.P("\t\treturn err")
		g.P("\t}")
	}
	g.P("\tif err := obj.Set(\"", clearMethodName, "\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\tfield := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Fields().ByName(", quoted(fieldName), ")")
	g.P("\t\tif err := builder.Clear(field); err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn obj")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
}

func emitOneofMethods(g *protogen.GeneratedFile, msg *protogen.Message, oneof *protogen.Oneof) {
	oneofName := string(oneof.Desc.Name())
	exportedOneofName := exportName(lowerCamel(oneofName))
	whichMethodName := "which" + exportedOneofName
	clearMethodName := "clear" + exportedOneofName
	g.P("\tif err := obj.Set(\"", whichMethodName, "\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\toneof := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Oneofs().ByName(", quoted(oneofName), ")")
	g.P("\t\tselected, err := builder.WhichOneof(oneof)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\tif selected == nil {")
	g.P("\t\t\treturn ", g.QualifiedGoIdent(gojaUndefinedIdent), "()")
	g.P("\t\t}")
	g.P("\t\treturn vm.ToValue(selected.JSONName())")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
	g.P("\tif err := obj.Set(\"", clearMethodName, "\", func() ", g.QualifiedGoIdent(gojaValueIdent), " {")
	g.P("\t\toneof := (&", g.QualifiedGoIdent(msg.GoIdent), "{}).ProtoReflect().Descriptor().Oneofs().ByName(", quoted(oneofName), ")")
	g.P("\t\tif err := builder.ClearOneof(oneof); err != nil {")
	g.P("\t\t\tpanic(vm.NewGoError(err))")
	g.P("\t\t}")
	g.P("\t\treturn obj")
	g.P("\t}); err != nil {")
	g.P("\t\treturn err")
	g.P("\t}")
}

func realOneofs(msg *protogen.Message) []*protogen.Oneof {
	out := make([]*protogen.Oneof, 0, len(msg.Oneofs))
	for _, oneof := range msg.Oneofs {
		if oneof.Desc.IsSynthetic() {
			continue
		}
		out = append(out, oneof)
	}
	return out
}

func oneofSelectionType(oneof *protogen.Oneof) string {
	values := make([]string, 0, len(oneof.Fields))
	for _, field := range oneof.Fields {
		values = append(values, quoted(field.Desc.JSONName()))
	}
	if len(values) == 0 {
		return "string"
	}
	return strings.Join(values, " | ")
}

func methodNameForField(field *protogen.Field) string {
	jsonName := field.Desc.JSONName()
	if jsonName != "" {
		return jsonName
	}
	return lowerCamel(string(field.Desc.Name()))
}

func fileIdentifier(path string) string {
	base := filepath.Base(path)
	var b strings.Builder
	capitalizeNext := true
	for _, r := range base {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if capitalizeNext {
				r = unicode.ToUpper(r)
			}
			b.WriteRune(r)
			capitalizeNext = false
			continue
		}
		capitalizeNext = true
	}
	if b.Len() == 0 {
		return "Proto"
	}
	return b.String()
}

func lowerFirst(s string) string {
	if s == "" {
		return "value"
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func exportName(s string) string {
	if s == "" {
		return "Field"
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func lowerCamel(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	if len(parts) == 0 {
		return "field"
	}
	for i := range parts {
		parts[i] = strings.ToLower(parts[i])
		if i > 0 {
			parts[i] = exportName(parts[i])
		}
	}
	return strings.Join(parts, "")
}

func quoted(s string) string {
	return strconv.Quote(s)
}
