// Code generated by logcopter-gen; DO NOT EDIT.

package generator

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.cmd.protoc-gen-goja-builder.internal.generator")
