title: "🚚 Move: relocate bun demo workspace"
description: "Move the bun demo JS workspace under cmd/bun-demo, add a local Makefile, update ignores and root Makefile, and refresh the embedded bundle."
tests:
  - "make -C cmd/bun-demo go-run-bun"
