title: "✨ Add: TSX demo bundle"
description: "Add a TSX-to-HTML demo bundle with a custom JSX runtime and new Makefile targets."
tests:
  - "make -C cmd/bun-demo go-run-bun-tsx"
  - "make -C cmd/bun-demo js-render-tsx"
