title: "✨ Demo: show SVG processing output"
description: "Enhance TS demo output with SVG metrics computed via lodash and update bundled asset." 
tests:
  - "make js-typecheck (pass)"
  - "make go-run-bun (pass)"
