// Code generated by xgoja; DO NOT EDIT.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"

	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	fixture "github.com/go-go-golems/go-go-goja/pkg/xgoja/testprovider"
)

const embeddedSpecJSON = `{
  "name": "embedded-jsverbs",
  "target": {
    "kind": "xgoja",
    "output": "dist/embedded-jsverbs"
  },
  "packages": [
    {
      "id": "fixture",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/testprovider",
      "register": "Register"
    }
  ],
  "runtimes": {
    "repl": {
      "modules": [
        {
          "package": "fixture",
          "name": "hello",
          "as": "hello"
        }
      ]
    }
  },
  "commands": {
    "eval": {
      "enabled": true,
      "runtime": "repl",
      "name": "eval"
    },
    "run": {
      "enabled": true,
      "runtime": "repl",
      "name": "run"
    },
    "repl": {
      "enabled": true,
      "runtime": "repl",
      "name": "repl"
    },
    "jsverbs": {
      "enabled": true,
      "runtime": "repl",
      "name": "verbs"
    }
  },
  "jsverbs": [
    {
      "id": "local",
      "path": "xgoja_embed/jsverbs/local",
      "embed": true
    }
  ]
}
`

//go:embed xgoja_embed/jsverbs/*
var embeddedJSVerbs embed.FS

func main() {
	registry := providerapi.NewRegistry()
	must(fixture.Register(registry))
	root, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON, EmbeddedJSVerbs: embeddedJSVerbs, EmbeddedHelp: nil})
	must(err)
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func decodeSpec() *app.Spec {
	spec := &app.Spec{}
	must(json.Unmarshal([]byte(embeddedSpecJSON), spec))
	return spec
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
