// Code generated by logcopter-gen; DO NOT EDIT.

package sdk

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.pkg.hashiplugin.sdk")
