// Code generated by xgoja; DO NOT EDIT.
package xgojaruntime

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/dop251/goja_nodejs/require"
	"github.com/go-go-golems/glazed/pkg/cli"
	"github.com/go-go-golems/glazed/pkg/cmds/values"
	"github.com/go-go-golems/go-go-goja/pkg/engine"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/dtsgen"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	fixture "github.com/go-go-golems/go-go-goja/pkg/xgoja/testprovider"
	"github.com/spf13/cobra"
)

const EmbeddedSpecJSON = `{
  "name": "generated-runtime-package",
  "appName": "generated-runtime-package",
  "target": {
    "kind": "package",
    "output": "internal/xgojaruntime"
  },
  "packages": [
    {
      "id": "fixture"
    }
  ],
  "modules": [
    {
      "package": "fixture",
      "name": "hello",
      "as": "hello"
    }
  ],
  "commands": {
    "eval": {
      "enabled": true,
      "name": "eval"
    },
    "run": {
      "enabled": false
    },
    "repl": {
      "enabled": false
    },
    "jsverbs": {
      "enabled": false
    }
  }
}
`

type Options struct {
	Out               io.Writer
	MiddlewaresFunc   cli.CobraMiddlewaresFunc
	ConfigureServices func(*app.HostServices)
}

type Bundle struct {
	Providers   *providerapi.ProviderRegistry
	RuntimePlan *app.RuntimePlan
	Host        *app.Host
}

func RegisterProviders(registry *providerapi.ProviderRegistry) error {
	if registry == nil {
		return fmt.Errorf("provider registry is nil")
	}
	if err := fixture.Register(registry); err != nil {
		return err
	}
	return nil
}

func DecodeSpec() (*app.RuntimePlan, error) {
	runtimePlan := &app.RuntimePlan{}
	if err := json.Unmarshal([]byte(EmbeddedSpecJSON), runtimePlan); err != nil {
		return nil, err
	}
	return runtimePlan, nil
}

func NewBundle(opts Options) (*Bundle, error) {
	registry := providerapi.NewProviderRegistry()
	if err := RegisterProviders(registry); err != nil {
		return nil, err
	}
	runtimePlan, err := DecodeSpec()
	if err != nil {
		return nil, err
	}
	host := app.NewHostWithOptions(registry, runtimePlan, app.HostOptions{
		Out:               opts.Out,
		MiddlewaresFunc:   opts.MiddlewaresFunc,
		ConfigureServices: opts.ConfigureServices,
	})
	return &Bundle{Providers: registry, RuntimePlan: runtimePlan, Host: host}, nil
}

func (b *Bundle) TypeScriptDeclarations() (string, error) {
	if b == nil || b.Host == nil {
		return "", fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	result, err := b.Host.TypeScriptDeclarations(dtsgen.Options{})
	if err != nil {
		return "", err
	}
	return result.DTS, nil
}

func (b *Bundle) WriteTypeScriptDeclarations(w io.Writer) error {
	if b == nil || b.Host == nil {
		return fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.WriteTypeScriptDeclarations(w, dtsgen.Options{})
}

func (b *Bundle) NewRuntime(ctx context.Context, opts ...require.Option) (*engine.Runtime, error) {
	if b == nil || b.Host == nil || b.Host.Factory == nil {
		return nil, fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.Factory.NewRuntime(ctx, opts...)
}

func (b *Bundle) NewRuntimeFromSections(ctx context.Context, vals *values.Values, opts ...require.Option) (*engine.Runtime, error) {
	if b == nil || b.Host == nil || b.Host.Factory == nil {
		return nil, fmt.Errorf("xgoja runtime bundle is not initialized")
	}
	return b.Host.Factory.NewRuntimeFromSections(ctx, vals, opts...)
}

func (b *Bundle) AttachDefaultCommands(root *cobra.Command) {
	if b == nil || b.Host == nil {
		return
	}
	b.Host.AttachDefaultCommands(root)
}
