// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: jsmodule.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JSModuleService_GetManifest_FullMethodName = "/hashiplugin.contract.v1.JSModuleService/GetManifest"
	JSModuleService_Invoke_FullMethodName      = "/hashiplugin.contract.v1.JSModuleService/Invoke"
)

// JSModuleServiceClient is the client API for JSModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JSModuleServiceClient interface {
	GetManifest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModuleManifest, error)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type jSModuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJSModuleServiceClient(cc grpc.ClientConnInterface) JSModuleServiceClient {
	return &jSModuleServiceClient{cc}
}

func (c *jSModuleServiceClient) GetManifest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ModuleManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModuleManifest)
	err := c.cc.Invoke(ctx, JSModuleService_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jSModuleServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, JSModuleService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JSModuleServiceServer is the server API for JSModuleService service.
// All implementations must embed UnimplementedJSModuleServiceServer
// for forward compatibility.
type JSModuleServiceServer interface {
	GetManifest(context.Context, *emptypb.Empty) (*ModuleManifest, error)
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedJSModuleServiceServer()
}

// UnimplementedJSModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJSModuleServiceServer struct{}

func (UnimplementedJSModuleServiceServer) GetManifest(context.Context, *emptypb.Empty) (*ModuleManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedJSModuleServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedJSModuleServiceServer) mustEmbedUnimplementedJSModuleServiceServer() {}
func (UnimplementedJSModuleServiceServer) testEmbeddedByValue()                         {}

// UnsafeJSModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JSModuleServiceServer will
// result in compilation errors.
type UnsafeJSModuleServiceServer interface {
	mustEmbedUnimplementedJSModuleServiceServer()
}

func RegisterJSModuleServiceServer(s grpc.ServiceRegistrar, srv JSModuleServiceServer) {
	// If the following call panics, it indicates UnimplementedJSModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JSModuleService_ServiceDesc, srv)
}

func _JSModuleService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JSModuleServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JSModuleService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JSModuleServiceServer).GetManifest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JSModuleService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JSModuleServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JSModuleService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JSModuleServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JSModuleService_ServiceDesc is the grpc.ServiceDesc for JSModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JSModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashiplugin.contract.v1.JSModuleService",
	HandlerType: (*JSModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _JSModuleService_GetManifest_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _JSModuleService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jsmodule.proto",
}
