// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: jsmodule.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportKind int32

const (
	ExportKind_EXPORT_KIND_UNSPECIFIED ExportKind = 0
	ExportKind_EXPORT_KIND_FUNCTION    ExportKind = 1
	ExportKind_EXPORT_KIND_OBJECT      ExportKind = 2
)

// Enum value maps for ExportKind.
var (
	ExportKind_name = map[int32]string{
		0: "EXPORT_KIND_UNSPECIFIED",
		1: "EXPORT_KIND_FUNCTION",
		2: "EXPORT_KIND_OBJECT",
	}
	ExportKind_value = map[string]int32{
		"EXPORT_KIND_UNSPECIFIED": 0,
		"EXPORT_KIND_FUNCTION":    1,
		"EXPORT_KIND_OBJECT":      2,
	}
)

func (x ExportKind) Enum() *ExportKind {
	p := new(ExportKind)
	*p = x
	return p
}

func (x ExportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_jsmodule_proto_enumTypes[0].Descriptor()
}

func (ExportKind) Type() protoreflect.EnumType {
	return &file_jsmodule_proto_enumTypes[0]
}

func (x ExportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportKind.Descriptor instead.
func (ExportKind) EnumDescriptor() ([]byte, []int) {
	return file_jsmodule_proto_rawDescGZIP(), []int{0}
}

type ModuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Exports       []*ExportSpec          `protobuf:"bytes,3,rep,name=exports,proto3" json:"exports,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Doc           string                 `protobuf:"bytes,5,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleManifest) Reset() {
	*x = ModuleManifest{}
	mi := &file_jsmodule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleManifest) ProtoMessage() {}

func (x *ModuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_jsmodule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleManifest.ProtoReflect.Descriptor instead.
func (*ModuleManifest) Descriptor() ([]byte, []int) {
	return file_jsmodule_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleManifest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModuleManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleManifest) GetExports() []*ExportSpec {
	if x != nil {
		return x.Exports
	}
	return nil
}

func (x *ModuleManifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ModuleManifest) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type ExportSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          ExportKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=hashiplugin.contract.v1.ExportKind" json:"kind,omitempty"`
	Methods       []string               `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	Doc           string                 `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSpec) Reset() {
	*x = ExportSpec{}
	mi := &file_jsmodule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSpec) ProtoMessage() {}

func (x *ExportSpec) ProtoReflect() protoreflect.Message {
	mi := &file_jsmodule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSpec.ProtoReflect.Descriptor instead.
func (*ExportSpec) Descriptor() ([]byte, []int) {
	return file_jsmodule_proto_rawDescGZIP(), []int{1}
}

func (x *ExportSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportSpec) GetKind() ExportKind {
	if x != nil {
		return x.Kind
	}
	return ExportKind_EXPORT_KIND_UNSPECIFIED
}

func (x *ExportSpec) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ExportSpec) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportName    string                 `protobuf:"bytes,1,opt,name=export_name,json=exportName,proto3" json:"export_name,omitempty"`
	MethodName    string                 `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Args          []*structpb.Value      `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_jsmodule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jsmodule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_jsmodule_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetExportName() string {
	if x != nil {
		return x.ExportName
	}
	return ""
}

func (x *InvokeRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *InvokeRequest) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Value        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_jsmodule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jsmodule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_jsmodule_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_jsmodule_proto protoreflect.FileDescriptor

const file_jsmodule_proto_rawDesc = "" +
	"\n" +
	"\x0ejsmodule.proto\x12\x17hashiplugin.contract.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc0\x01\n" +
	"\x0eModuleManifest\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\aexports\x18\x03 \x03(\v2#.hashiplugin.contract.v1.ExportSpecR\aexports\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x10\n" +
	"\x03doc\x18\x05 \x01(\tR\x03doc\"\x85\x01\n" +
	"\n" +
	"ExportSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x04kind\x18\x02 \x01(\x0e2#.hashiplugin.contract.v1.ExportKindR\x04kind\x12\x18\n" +
	"\amethods\x18\x03 \x03(\tR\amethods\x12\x10\n" +
	"\x03doc\x18\x04 \x01(\tR\x03doc\"}\n" +
	"\rInvokeRequest\x12\x1f\n" +
	"\vexport_name\x18\x01 \x01(\tR\n" +
	"exportName\x12\x1f\n" +
	"\vmethod_name\x18\x02 \x01(\tR\n" +
	"methodName\x12*\n" +
	"\x04args\x18\x03 \x03(\v2\x16.google.protobuf.ValueR\x04args\"@\n" +
	"\x0eInvokeResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06result*[\n" +
	"\n" +
	"ExportKind\x12\x1b\n" +
	"\x17EXPORT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EXPORT_KIND_FUNCTION\x10\x01\x12\x16\n" +
	"\x12EXPORT_KIND_OBJECT\x10\x022\xbc\x01\n" +
	"\x0fJSModuleService\x12N\n" +
	"\vGetManifest\x12\x16.google.protobuf.Empty\x1a'.hashiplugin.contract.v1.ModuleManifest\x12Y\n" +
	"\x06Invoke\x12&.hashiplugin.contract.v1.InvokeRequest\x1a'.hashiplugin.contract.v1.InvokeResponseBFZDgithub.com/go-go-golems/go-go-goja/pkg/hashiplugin/contract;contractb\x06proto3"

var (
	file_jsmodule_proto_rawDescOnce sync.Once
	file_jsmodule_proto_rawDescData []byte
)

func file_jsmodule_proto_rawDescGZIP() []byte {
	file_jsmodule_proto_rawDescOnce.Do(func() {
		file_jsmodule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jsmodule_proto_rawDesc), len(file_jsmodule_proto_rawDesc)))
	})
	return file_jsmodule_proto_rawDescData
}

var file_jsmodule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jsmodule_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jsmodule_proto_goTypes = []any{
	(ExportKind)(0),        // 0: hashiplugin.contract.v1.ExportKind
	(*ModuleManifest)(nil), // 1: hashiplugin.contract.v1.ModuleManifest
	(*ExportSpec)(nil),     // 2: hashiplugin.contract.v1.ExportSpec
	(*InvokeRequest)(nil),  // 3: hashiplugin.contract.v1.InvokeRequest
	(*InvokeResponse)(nil), // 4: hashiplugin.contract.v1.InvokeResponse
	(*structpb.Value)(nil), // 5: google.protobuf.Value
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_jsmodule_proto_depIdxs = []int32{
	2, // 0: hashiplugin.contract.v1.ModuleManifest.exports:type_name -> hashiplugin.contract.v1.ExportSpec
	0, // 1: hashiplugin.contract.v1.ExportSpec.kind:type_name -> hashiplugin.contract.v1.ExportKind
	5, // 2: hashiplugin.contract.v1.InvokeRequest.args:type_name -> google.protobuf.Value
	5, // 3: hashiplugin.contract.v1.InvokeResponse.result:type_name -> google.protobuf.Value
	6, // 4: hashiplugin.contract.v1.JSModuleService.GetManifest:input_type -> google.protobuf.Empty
	3, // 5: hashiplugin.contract.v1.JSModuleService.Invoke:input_type -> hashiplugin.contract.v1.InvokeRequest
	1, // 6: hashiplugin.contract.v1.JSModuleService.GetManifest:output_type -> hashiplugin.contract.v1.ModuleManifest
	4, // 7: hashiplugin.contract.v1.JSModuleService.Invoke:output_type -> hashiplugin.contract.v1.InvokeResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jsmodule_proto_init() }
func file_jsmodule_proto_init() {
	if File_jsmodule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jsmodule_proto_rawDesc), len(file_jsmodule_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jsmodule_proto_goTypes,
		DependencyIndexes: file_jsmodule_proto_depIdxs,
		EnumInfos:         file_jsmodule_proto_enumTypes,
		MessageInfos:      file_jsmodule_proto_msgTypes,
	}.Build()
	File_jsmodule_proto = out.File
	file_jsmodule_proto_goTypes = nil
	file_jsmodule_proto_depIdxs = nil
}
