// Code generated by protoc-gen-goja-builder. DO NOT EDIT.
// source: task.proto

package taskpb

import (
	errors "errors"
	goja "github.com/dop251/goja"
	require "github.com/dop251/goja_nodejs/require"
	modules "github.com/go-go-golems/go-go-goja/modules"
	protogoja "github.com/go-go-golems/go-go-goja/pkg/protogoja"
	spec "github.com/go-go-golems/go-go-goja/pkg/tsgen/spec"
	proto "google.golang.org/protobuf/proto"
)

// GojaBuilderFileTaskProtoModuleName returns the JavaScript module name for this generated protobuf builder companion file.
func GojaBuilderFileTaskProtoModuleName() string {
	return "examples.xgoja.protobuf.v1"
}

// GojaBuilderFileTaskProtoMessageTypes returns the full protobuf message names exported by this generated builder companion file.
func GojaBuilderFileTaskProtoMessageTypes() []string {
	return []string{
		"examples.xgoja.protobuf.v1.Task",
		"examples.xgoja.protobuf.v1.TaskEnvelope",
	}
}

// GojaBuilderFileTaskProtoTypeScriptModule returns the TypeScript declaration descriptor for this generated protobuf builder companion file.
func GojaBuilderFileTaskProtoTypeScriptModule(moduleName string) *spec.Module {
	if moduleName == "" {
		moduleName = GojaBuilderFileTaskProtoModuleName()
	}
	return &spec.Module{
		Name: moduleName,
		RawDTS: []string{
			"export interface ProtoMessage<TTypeName extends string = string> {",
			"  readonly typeName: TTypeName;",
			"  toJSON(): unknown;",
			"  clone(): ProtoMessage<TTypeName>;",
			"  equals(other: unknown): boolean;",
			"}",
			"export interface MessageNamespace<TMessage, TBuilder> {",
			"  readonly typeName: string;",
			"  builder(): TBuilder;",
			"  from(value: TMessage): TMessage;",
			"  is(value: unknown): value is TMessage;",
			"  clone(value: TMessage): TMessage;",
			"}",
			"export const TaskPriority: {",
			"  readonly typeName: \"examples.xgoja.protobuf.v1.TaskPriority\";",
			"  readonly TASK_PRIORITY_UNSPECIFIED: 0;",
			"  readonly TASK_PRIORITY_LOW: 1;",
			"  readonly TASK_PRIORITY_HIGH: 2;",
			"};",
			"export type TaskPriorityValue = 0 | 1 | 2;",
			"export interface Task extends ProtoMessage<\"examples.xgoja.protobuf.v1.Task\"> {}",
			"export interface TaskBuilder {",
			"  id(value: string): this;",
			"  clearId(): this;",
			"  title(value: string): this;",
			"  clearTitle(): this;",
			"  tags(value: string[]): this;",
			"  addTags(value: string): this;",
			"  clearTags(): this;",
			"  labels(value: Record<string, string>): this;",
			"  putLabels(key: string, value: string): this;",
			"  deleteLabels(key: string): this;",
			"  clearLabels(): this;",
			"  priority(value: TaskPriorityValue | keyof typeof TaskPriority): this;",
			"  clearPriority(): this;",
			"  dueAt(value: Timestamp): this;",
			"  hasDueAt(): boolean;",
			"  clearDueAt(): this;",
			"  metadata(value: Struct): this;",
			"  hasMetadata(): boolean;",
			"  clearMetadata(): this;",
			"  build(): Task;",
			"  clone(): TaskBuilder;",
			"}",
			"export const Task: MessageNamespace<Task, TaskBuilder>;",
			"export interface TaskEnvelope extends ProtoMessage<\"examples.xgoja.protobuf.v1.TaskEnvelope\"> {}",
			"export interface TaskEnvelopeBuilder {",
			"  task(value: Task): this;",
			"  hasTask(): boolean;",
			"  clearTask(): this;",
			"  source(value: string): this;",
			"  clearSource(): this;",
			"  build(): TaskEnvelope;",
			"  clone(): TaskEnvelopeBuilder;",
			"}",
			"export const TaskEnvelope: MessageNamespace<TaskEnvelope, TaskEnvelopeBuilder>;",
		},
	}
}

// NewGojaBuilderFileTaskProtoLoader returns a CommonJS module loader for this generated protobuf builder companion file.
func NewGojaBuilderFileTaskProtoLoader(moduleName string) require.ModuleLoader {
	return func(vm *goja.Runtime, moduleObj *goja.Object) {
		exports := moduleObj.Get("exports").ToObject(vm)
		taskPriority, err := NewTaskPriorityGojaEnum(vm)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		if err := exports.Set("TaskPriority", taskPriority); err != nil {
			panic(vm.NewGoError(err))
		}
		task, err := NewTaskGojaNamespace(vm)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		if err := exports.Set("Task", task); err != nil {
			panic(vm.NewGoError(err))
		}
		taskEnvelope, err := NewTaskEnvelopeGojaNamespace(vm)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		if err := exports.Set("TaskEnvelope", taskEnvelope); err != nil {
			panic(vm.NewGoError(err))
		}
	}
}

// RegisterGojaBuilderFileTaskProtoModule registers this generated protobuf builder module in a goja require registry.
func RegisterGojaBuilderFileTaskProtoModule(reg *require.Registry, moduleName string) error {
	if reg == nil {
		return errors.New("protogoja: nil require registry")
	}
	if moduleName == "" {
		moduleName = GojaBuilderFileTaskProtoModuleName()
	}
	reg.RegisterNativeModule(moduleName, NewGojaBuilderFileTaskProtoLoader(moduleName))
	return nil
}

// GojaBuilderFileTaskProtoModule returns a modules.NativeModule wrapper for this generated protobuf builder module.
func GojaBuilderFileTaskProtoModule(moduleName string) modules.NativeModule {
	if moduleName == "" {
		moduleName = GojaBuilderFileTaskProtoModuleName()
	}
	return &gojaBuilderFileTaskProtoModule{name: moduleName}
}

type gojaBuilderFileTaskProtoModule struct{ name string }

func (m *gojaBuilderFileTaskProtoModule) Name() string { return m.name }
func (m *gojaBuilderFileTaskProtoModule) Doc() string {
	return "Generated protobuf Goja builder module for examples.xgoja.protobuf.v1"
}
func (m *gojaBuilderFileTaskProtoModule) Loader(vm *goja.Runtime, moduleObj *goja.Object) {
	NewGojaBuilderFileTaskProtoLoader(m.name)(vm, moduleObj)
}
func (m *gojaBuilderFileTaskProtoModule) TypeScriptModule() *spec.Module {
	return GojaBuilderFileTaskProtoTypeScriptModule(m.name)
}

// RegisterGojaBuilderFileTaskProtoMessageTypes calls register for every message type exported by this generated builder companion file.
func RegisterGojaBuilderFileTaskProtoMessageTypes(register func(string, proto.Message) error) error {
	if register == nil {
		return errors.New("protogoja: nil message type register function")
	}
	if err := register("examples.xgoja.protobuf.v1.Task", &Task{}); err != nil {
		return err
	}
	if err := register("examples.xgoja.protobuf.v1.TaskEnvelope", &TaskEnvelope{}); err != nil {
		return err
	}
	return nil
}

// NewTaskPriorityGojaEnum returns the JavaScript enum export object for examples.xgoja.protobuf.v1.TaskPriority.
func NewTaskPriorityGojaEnum(vm *goja.Runtime) (*goja.Object, error) {
	if vm == nil {
		return nil, errors.New("protogoja: nil runtime")
	}
	obj := vm.NewObject()
	if err := obj.Set("typeName", "examples.xgoja.protobuf.v1.TaskPriority"); err != nil {
		return nil, err
	}
	if err := obj.Set("TASK_PRIORITY_UNSPECIFIED", 0); err != nil {
		return nil, err
	}
	if err := obj.Set("TASK_PRIORITY_LOW", 1); err != nil {
		return nil, err
	}
	if err := obj.Set("TASK_PRIORITY_HIGH", 2); err != nil {
		return nil, err
	}
	return obj, nil
}

// NewTaskGojaNamespace returns the JavaScript namespace object for examples.xgoja.protobuf.v1.Task.
func NewTaskGojaNamespace(vm *goja.Runtime) (*goja.Object, error) {
	if vm == nil {
		return nil, errors.New("protogoja: nil runtime")
	}
	obj := vm.NewObject()
	if err := protogoja.AttachMessagePrototype(vm, obj, &Task{}); err != nil {
		return nil, err
	}
	if err := obj.Set("typeName", "examples.xgoja.protobuf.v1.Task"); err != nil {
		return nil, err
	}
	if err := obj.Set("builder", func() goja.Value {
		builder, err := NewTaskGojaBuilder(vm)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return builder
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("from", func(value goja.Value) goja.Value {
		msg, ok := protogoja.MessageFromValue(value)
		if !ok || msg.ProtoReflect().Descriptor().FullName() != (&Task{}).ProtoReflect().Descriptor().FullName() {
			panic(vm.NewTypeError("value is not a examples.xgoja.protobuf.v1.Task ProtoMessage"))
		}
		out, err := protogoja.ToValue(vm, msg)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("is", func(value goja.Value) bool {
		return protogoja.IsMessageValueOf(value, (&Task{}).ProtoReflect().Descriptor().FullName())
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("clone", func(value goja.Value) goja.Value {
		msg, ok := protogoja.MessageFromValue(value)
		if !ok || msg.ProtoReflect().Descriptor().FullName() != (&Task{}).ProtoReflect().Descriptor().FullName() {
			panic(vm.NewTypeError("value is not a examples.xgoja.protobuf.v1.Task ProtoMessage"))
		}
		out, err := protogoja.ToValue(vm, msg)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return nil, err
	}
	return obj, nil
}

// NewTaskGojaBuilder returns a JavaScript fluent builder object for examples.xgoja.protobuf.v1.Task.
func NewTaskGojaBuilder(vm *goja.Runtime) (*goja.Object, error) {
	if vm == nil {
		return nil, errors.New("protogoja: nil runtime")
	}
	builder, err := protogoja.NewBuilder(&Task{})
	if err != nil {
		return nil, err
	}
	obj := vm.NewObject()
	if err := protogoja.AttachBuilderRef(vm, obj, builder); err != nil {
		return nil, err
	}
	if err := attachTaskGojaBuilderMethods(vm, obj, builder); err != nil {
		return nil, err
	}
	return obj, nil
}

func attachTaskGojaBuilderMethods(vm *goja.Runtime, obj *goja.Object, builder *protogoja.BuilderRef) error {
	if err := obj.Set("build", func() goja.Value {
		out, err := protogoja.ToValue(vm, builder.Build())
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return err
	}
	if err := obj.Set("clone", func() goja.Value {
		cloned, err := builder.Clone()
		if err != nil {
			panic(vm.NewGoError(err))
		}
		cloneObj := vm.NewObject()
		if err := protogoja.AttachBuilderRef(vm, cloneObj, cloned); err != nil {
			panic(vm.NewGoError(err))
		}
		if err := attachTaskGojaBuilderMethods(vm, cloneObj, cloned); err != nil {
			panic(vm.NewGoError(err))
		}
		return cloneObj
	}); err != nil {
		return err
	}
	if err := obj.Set("id", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("id")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearId", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("id")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("title", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("title")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearTitle", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("title")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("tags", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("tags")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("addTags", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("tags")
		if err := builder.Add(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearTags", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("tags")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("labels", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("labels")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("putLabels", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("labels")
		if err := builder.Put(vm, field, call.Argument(0), call.Argument(1)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("deleteLabels", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("labels")
		if err := builder.Delete(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearLabels", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("labels")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("priority", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("priority")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearPriority", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("priority")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("dueAt", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("due_at")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("hasDueAt", func() bool {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("due_at")
		has, err := builder.Has(field)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return has
	}); err != nil {
		return err
	}
	if err := obj.Set("clearDueAt", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("due_at")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("metadata", func(call goja.FunctionCall) goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("metadata")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("hasMetadata", func() bool {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("metadata")
		has, err := builder.Has(field)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return has
	}); err != nil {
		return err
	}
	if err := obj.Set("clearMetadata", func() goja.Value {
		field := (&Task{}).ProtoReflect().Descriptor().Fields().ByName("metadata")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	return nil
}

// NewTaskEnvelopeGojaNamespace returns the JavaScript namespace object for examples.xgoja.protobuf.v1.TaskEnvelope.
func NewTaskEnvelopeGojaNamespace(vm *goja.Runtime) (*goja.Object, error) {
	if vm == nil {
		return nil, errors.New("protogoja: nil runtime")
	}
	obj := vm.NewObject()
	if err := protogoja.AttachMessagePrototype(vm, obj, &TaskEnvelope{}); err != nil {
		return nil, err
	}
	if err := obj.Set("typeName", "examples.xgoja.protobuf.v1.TaskEnvelope"); err != nil {
		return nil, err
	}
	if err := obj.Set("builder", func() goja.Value {
		builder, err := NewTaskEnvelopeGojaBuilder(vm)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return builder
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("from", func(value goja.Value) goja.Value {
		msg, ok := protogoja.MessageFromValue(value)
		if !ok || msg.ProtoReflect().Descriptor().FullName() != (&TaskEnvelope{}).ProtoReflect().Descriptor().FullName() {
			panic(vm.NewTypeError("value is not a examples.xgoja.protobuf.v1.TaskEnvelope ProtoMessage"))
		}
		out, err := protogoja.ToValue(vm, msg)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("is", func(value goja.Value) bool {
		return protogoja.IsMessageValueOf(value, (&TaskEnvelope{}).ProtoReflect().Descriptor().FullName())
	}); err != nil {
		return nil, err
	}
	if err := obj.Set("clone", func(value goja.Value) goja.Value {
		msg, ok := protogoja.MessageFromValue(value)
		if !ok || msg.ProtoReflect().Descriptor().FullName() != (&TaskEnvelope{}).ProtoReflect().Descriptor().FullName() {
			panic(vm.NewTypeError("value is not a examples.xgoja.protobuf.v1.TaskEnvelope ProtoMessage"))
		}
		out, err := protogoja.ToValue(vm, msg)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return nil, err
	}
	return obj, nil
}

// NewTaskEnvelopeGojaBuilder returns a JavaScript fluent builder object for examples.xgoja.protobuf.v1.TaskEnvelope.
func NewTaskEnvelopeGojaBuilder(vm *goja.Runtime) (*goja.Object, error) {
	if vm == nil {
		return nil, errors.New("protogoja: nil runtime")
	}
	builder, err := protogoja.NewBuilder(&TaskEnvelope{})
	if err != nil {
		return nil, err
	}
	obj := vm.NewObject()
	if err := protogoja.AttachBuilderRef(vm, obj, builder); err != nil {
		return nil, err
	}
	if err := attachTaskEnvelopeGojaBuilderMethods(vm, obj, builder); err != nil {
		return nil, err
	}
	return obj, nil
}

func attachTaskEnvelopeGojaBuilderMethods(vm *goja.Runtime, obj *goja.Object, builder *protogoja.BuilderRef) error {
	if err := obj.Set("build", func() goja.Value {
		out, err := protogoja.ToValue(vm, builder.Build())
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return out
	}); err != nil {
		return err
	}
	if err := obj.Set("clone", func() goja.Value {
		cloned, err := builder.Clone()
		if err != nil {
			panic(vm.NewGoError(err))
		}
		cloneObj := vm.NewObject()
		if err := protogoja.AttachBuilderRef(vm, cloneObj, cloned); err != nil {
			panic(vm.NewGoError(err))
		}
		if err := attachTaskEnvelopeGojaBuilderMethods(vm, cloneObj, cloned); err != nil {
			panic(vm.NewGoError(err))
		}
		return cloneObj
	}); err != nil {
		return err
	}
	if err := obj.Set("task", func(call goja.FunctionCall) goja.Value {
		field := (&TaskEnvelope{}).ProtoReflect().Descriptor().Fields().ByName("task")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("hasTask", func() bool {
		field := (&TaskEnvelope{}).ProtoReflect().Descriptor().Fields().ByName("task")
		has, err := builder.Has(field)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		return has
	}); err != nil {
		return err
	}
	if err := obj.Set("clearTask", func() goja.Value {
		field := (&TaskEnvelope{}).ProtoReflect().Descriptor().Fields().ByName("task")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("source", func(call goja.FunctionCall) goja.Value {
		field := (&TaskEnvelope{}).ProtoReflect().Descriptor().Fields().ByName("source")
		if err := builder.Set(vm, field, call.Argument(0)); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	if err := obj.Set("clearSource", func() goja.Value {
		field := (&TaskEnvelope{}).ProtoReflect().Descriptor().Fields().ByName("source")
		if err := builder.Clear(field); err != nil {
			panic(vm.NewGoError(err))
		}
		return obj
	}); err != nil {
		return err
	}
	return nil
}
