// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT.

declare module "crypto" {
  export function createHash(algorithm: string): unknown;
  export function randomBytes(size: number): Buffer;
  export function randomUUID(): string;
}

declare module "database" {
  export function close(): void;
  export function configure(driverName: string, dataSourceName: string): void;
  export function exec(query: string, ...args: unknown[]): unknown;
  export function query(query: string, ...args: unknown[]): unknown;
}

declare module "events" {
  type EventName = string | symbol;
  type Listener = (...args: any[]) => void;
  class EventEmitter {
  constructor();
  on(name: EventName, listener: Listener): this;
  addListener(name: EventName, listener: Listener): this;
  once(name: EventName, listener: Listener): this;
  off(name: EventName, listener: Listener): this;
  removeListener(name: EventName, listener: Listener): this;
  removeAllListeners(name?: EventName): this;
  emit(name: EventName, ...args: any[]): boolean;
  listeners(name: EventName): Listener[];
  rawListeners(name: EventName): Listener[];
  listenerCount(name: EventName): number;
  eventNames(): EventName[];
  }
  export = EventEmitter;
  export { EventEmitter };
}

declare module "exec" {
  export function run(cmd: string, args: string[]): string;
}

declare module "fs" {
  export function appendFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function appendFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  export function copyFile(src: string, dst: string): Promise<void>;
  export function copyFileSync(src: string, dst: string): void;
  export function exists(path: string): Promise<boolean>;
  export function existsSync(path: string): boolean;
  export function mkdir(path: string, options?: {  }): Promise<void>;
  export function mkdirSync(path: string, options?: {  }): void;
  export function readFile(path: string, encoding?: string | {  }): Promise<string | Buffer>;
  export function readFileSync(path: string, encoding?: string | {  }): string | Buffer;
  export function readdir(path: string): Promise<string[]>;
  export function readdirSync(path: string): string[];
  export function rename(oldPath: string, newPath: string): Promise<void>;
  export function renameSync(oldPath: string, newPath: string): void;
  export function rm(path: string, options?: {  }): Promise<void>;
  export function rmSync(path: string, options?: {  }): void;
  export function stat(path: string): Promise<FileStats>;
  export function statSync(path: string): FileStats;
  export function unlink(path: string): Promise<void>;
  export function unlinkSync(path: string): void;
  export function writeFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function writeFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  interface FileStats {
  name: string;
  size: number;
  mode: number;
  modTime: string;
  isDir: boolean;
  isFile: boolean;
  }
}

declare module "node:crypto" {
  export function createHash(algorithm: string): unknown;
  export function randomBytes(size: number): Buffer;
  export function randomUUID(): string;
}

declare module "node:events" {
  type EventName = string | symbol;
  type Listener = (...args: any[]) => void;
  class EventEmitter {
  constructor();
  on(name: EventName, listener: Listener): this;
  addListener(name: EventName, listener: Listener): this;
  once(name: EventName, listener: Listener): this;
  off(name: EventName, listener: Listener): this;
  removeListener(name: EventName, listener: Listener): this;
  removeAllListeners(name?: EventName): this;
  emit(name: EventName, ...args: any[]): boolean;
  listeners(name: EventName): Listener[];
  rawListeners(name: EventName): Listener[];
  listenerCount(name: EventName): number;
  eventNames(): EventName[];
  }
  export = EventEmitter;
  export { EventEmitter };
}

declare module "node:fs" {
  export function appendFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function appendFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  export function copyFile(src: string, dst: string): Promise<void>;
  export function copyFileSync(src: string, dst: string): void;
  export function exists(path: string): Promise<boolean>;
  export function existsSync(path: string): boolean;
  export function mkdir(path: string, options?: {  }): Promise<void>;
  export function mkdirSync(path: string, options?: {  }): void;
  export function readFile(path: string, encoding?: string | {  }): Promise<string | Buffer>;
  export function readFileSync(path: string, encoding?: string | {  }): string | Buffer;
  export function readdir(path: string): Promise<string[]>;
  export function readdirSync(path: string): string[];
  export function rename(oldPath: string, newPath: string): Promise<void>;
  export function renameSync(oldPath: string, newPath: string): void;
  export function rm(path: string, options?: {  }): Promise<void>;
  export function rmSync(path: string, options?: {  }): void;
  export function stat(path: string): Promise<FileStats>;
  export function statSync(path: string): FileStats;
  export function unlink(path: string): Promise<void>;
  export function unlinkSync(path: string): void;
  export function writeFile(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): Promise<void>;
  export function writeFileSync(path: string, data: string | Buffer | Uint8Array | DataView, encoding?: string | {  }): void;
  interface FileStats {
  name: string;
  size: number;
  mode: number;
  modTime: string;
  isDir: boolean;
  isFile: boolean;
  }
}

declare module "node:os" {
  export function arch(): string;
  export function cpus(): {  }[];
  export function homedir(): string;
  export function hostname(): string;
  export function platform(): string;
  export function release(): string;
  export function tmpdir(): string;
  export function type(): string;
}

declare module "node:path" {
  export function basename(path: string): string;
  export function dirname(path: string): string;
  export function extname(path: string): string;
  export function isAbsolute(path: string): boolean;
  export function join(...parts: string[]): string;
  export function relative(from: string, to: string): string;
  export function resolve(...parts: string[]): string;
}

declare module "os" {
  export function arch(): string;
  export function cpus(): {  }[];
  export function homedir(): string;
  export function hostname(): string;
  export function platform(): string;
  export function release(): string;
  export function tmpdir(): string;
  export function type(): string;
}

declare module "path" {
  export function basename(path: string): string;
  export function dirname(path: string): string;
  export function extname(path: string): string;
  export function isAbsolute(path: string): boolean;
  export function join(...parts: string[]): string;
  export function relative(from: string, to: string): string;
  export function resolve(...parts: string[]): string;
}

declare module "yaml" {
  export function parse(input: string): any;
  export function stringify(value: any, options?: { indent?: number }): string;
  export function validate(input: string): { errors?: string[]; valid: boolean };
}
