// Code generated by logcopter-gen; DO NOT EDIT.

package express

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.modules.express")
