package generate

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-go-golems/go-go-goja/cmd/xgoja/internal/buildspec"
)

func TestRenderGoModDeterministic(t *testing.T) {
	spec := fixtureSpec()
	got := RenderGoMod(spec, Options{XGojaModuleVersion: "v0.1.0", XGojaReplace: "../go-go-goja"})
	for _, want := range []string{
		"module example.com/generated/fixture",
		"go 1.26",
		"github.com/go-go-golems/go-go-goja v0.1.0",
		"github.com/go-go-golems/web-stuff v0.3.0",
		"replace github.com/go-go-golems/go-go-goja => ../go-go-goja",
		"replace github.com/go-go-golems/web-stuff => ../web-stuff",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected go.mod to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderMainRegistersProviders(t *testing.T) {
	got := RenderMain(fixtureSpec())
	for _, want := range []string{
		"// Code generated by xgoja; DO NOT EDIT.",
		"providerapi.NewRegistry()",
		"core.Register(registry)",
		"web.Register(registry)",
		"const embeddedSpecJSON = `",
		"app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON})",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecStableShape(t *testing.T) {
	got := RenderEmbeddedSpec(fixtureSpec())
	for _, want := range []string{
		`"name": "fixture"`,
		`"kind": "xgoja"`,
		`"package": "web"`,
		`"as": "fetch"`,
		`"runtime": "repl"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestWriteAll(t *testing.T) {
	dir := t.TempDir()
	if err := WriteAll(dir, fixtureSpec(), Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, name := range []string{"go.mod", "main.go", "xgoja.gen.json"} {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read generated %s: %v", name, err)
		}
		if len(data) == 0 {
			t.Fatalf("generated %s is empty", name)
		}
	}
}

func TestGeneratedProgramRunsFixtureProvider(t *testing.T) {
	runGeneratedEval(t, buildableSpec("xgoja", "", ""))
}

func TestGeneratedCobraTargetAttachesCommands(t *testing.T) {
	runGeneratedEval(t, buildableSpec("cobra", "github.com/go-go-golems/go-go-goja/pkg/xgoja/testcobra", "NewRootCommand"))
}

func TestGeneratedAdapterTargetUsesAdapterBuild(t *testing.T) {
	runGeneratedEval(t, buildableSpec("adapter", "github.com/go-go-golems/go-go-goja/pkg/xgoja/testadapter", ""))
}

func runGeneratedEval(t *testing.T, spec *buildspec.Spec) {
	t.Helper()
	repoRoot, err := filepath.Abs("../../../..")
	if err != nil {
		t.Fatalf("repo root: %v", err)
	}
	dir := t.TempDir()
	if err := WriteAll(dir, spec, Options{XGojaModuleVersion: "v0.0.0", XGojaReplace: repoRoot}); err != nil {
		t.Fatalf("write generated program: %v", err)
	}
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy: %v\n%s", err, out)
	}
	cmd = exec.Command("go", "run", ".", "eval", `require("hello").greet("intern")`)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go run generated program: %v\n%s", err, out)
	}
	if strings.TrimSpace(string(out)) != "hello intern" {
		t.Fatalf("generated output = %q", out)
	}
}

func buildableSpec(kind, targetImport, root string) *buildspec.Spec {
	return &buildspec.Spec{
		Name:   "fixture",
		Go:     buildspec.GoSpec{Version: "1.26", Module: "example.com/generated/fixture"},
		Target: buildspec.TargetSpec{Kind: kind, Import: targetImport, Root: root, Output: "dist/fixture"},
		Packages: []buildspec.PackageSpec{
			{ID: "fixture", Import: "github.com/go-go-golems/go-go-goja/pkg/xgoja/testprovider", Register: "Register"},
		},
		Runtimes: map[string]buildspec.Runtime{
			"repl": {Modules: []buildspec.ModuleInstance{{Package: "fixture", Name: "hello", As: "hello"}}},
		},
		Commands: buildspec.CommandsSpec{Repl: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "repl"}},
	}
}

func fixtureSpec() *buildspec.Spec {
	return &buildspec.Spec{
		Name: "fixture",
		Go: buildspec.GoSpec{
			Version: "1.26",
			Module:  "example.com/generated/fixture",
		},
		Target: buildspec.TargetSpec{Kind: "xgoja", Output: "dist/fixture"},
		Packages: []buildspec.PackageSpec{
			{ID: "core", Import: "github.com/go-go-golems/go-go-goja/xgoja", Register: "Register"},
			{ID: "web", Import: "github.com/go-go-golems/web-stuff/xgoja", Version: "v0.3.0", Register: "Register", Replace: "../web-stuff"},
		},
		Runtimes: map[string]buildspec.Runtime{
			"repl": {Modules: []buildspec.ModuleInstance{{Package: "web", Name: "fetch", As: "fetch"}}},
		},
		Commands: buildspec.CommandsSpec{Repl: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "repl"}},
	}
}
