package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-go-golems/go-go-goja/cmd/xgoja/internal/buildspec"
)

func TestRenderGoModDeterministic(t *testing.T) {
	spec := fixtureSpec()
	got := RenderGoMod(spec, Options{XGojaModuleVersion: "v0.1.0", XGojaReplace: "../go-go-goja"})
	for _, want := range []string{
		"module example.com/generated/fixture",
		"go 1.26",
		"github.com/go-go-golems/go-go-goja v0.1.0",
		"github.com/go-go-golems/web-stuff v0.3.0",
		"replace github.com/go-go-golems/go-go-goja => ../go-go-goja",
		"replace github.com/go-go-golems/web-stuff => ../web-stuff",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected go.mod to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderMainRegistersProviders(t *testing.T) {
	got := RenderMain(fixtureSpec())
	for _, want := range []string{
		"// Code generated by xgoja; DO NOT EDIT.",
		"providerapi.NewRegistry()",
		"core.Register(registry)",
		"web.Register(registry)",
		"const embeddedSpecJSON = `",
		"xgoja generated binary registered %d provider package(s)",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecStableShape(t *testing.T) {
	got := RenderEmbeddedSpec(fixtureSpec())
	for _, want := range []string{
		`"name": "fixture"`,
		`"kind": "xgoja"`,
		`"package": "web"`,
		`"as": "fetch"`,
		`"runtime": "repl"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestWriteAll(t *testing.T) {
	dir := t.TempDir()
	if err := WriteAll(dir, fixtureSpec(), Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, name := range []string{"go.mod", "main.go", "xgoja.gen.json"} {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read generated %s: %v", name, err)
		}
		if len(data) == 0 {
			t.Fatalf("generated %s is empty", name)
		}
	}
}

func fixtureSpec() *buildspec.Spec {
	return &buildspec.Spec{
		Name: "fixture",
		Go: buildspec.GoSpec{
			Version: "1.26",
			Module:  "example.com/generated/fixture",
		},
		Target: buildspec.TargetSpec{Kind: "xgoja", Output: "dist/fixture"},
		Packages: []buildspec.PackageSpec{
			{ID: "core", Import: "github.com/go-go-golems/go-go-goja/xgoja", Register: "Register"},
			{ID: "web", Import: "github.com/go-go-golems/web-stuff/xgoja", Version: "v0.3.0", Register: "Register", Replace: "../web-stuff"},
		},
		Runtimes: map[string]buildspec.Runtime{
			"repl": {Modules: []buildspec.ModuleInstance{{Package: "web", Name: "fetch", As: "fetch"}}},
		},
		Commands: buildspec.CommandsSpec{Repl: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "repl"}},
	}
}
