package generate

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/go-go-golems/go-go-goja/cmd/xgoja/internal/buildspec"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
)

func TestRenderGoModDeterministic(t *testing.T) {
	buildSpec := fixtureSpec()
	got := RenderGoMod(buildSpec, Options{XGojaModuleVersion: "v0.1.0", XGojaReplace: "../go-go-goja"})
	for _, want := range []string{
		"module example.com/generated/fixture",
		"go 1.26",
		"github.com/go-go-golems/go-go-goja v0.1.0",
		"github.com/go-go-golems/web-stuff v0.3.0",
		"replace github.com/go-go-golems/go-go-goja => ../go-go-goja",
		"replace github.com/go-go-golems/web-stuff => ../web-stuff",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected go.mod to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderGoModResolvesRelativePackageReplaceFromSpecBaseDir(t *testing.T) {
	buildSpec := fixtureSpec()
	buildSpec.BaseDir = filepath.Join(string(filepath.Separator), "tmp", "example")
	got := RenderGoMod(buildSpec, Options{XGojaModuleVersion: "v0.1.0"})
	want := "replace github.com/go-go-golems/web-stuff => /tmp/web-stuff"
	if !strings.Contains(got, want) {
		t.Fatalf("expected go.mod to contain %q, got:\n%s", want, got)
	}
}

func TestRenderGoModUsesModuleRootsForSubpackageImports(t *testing.T) {
	buildSpec := &buildspec.BuildSpec{
		Name: "subpackage-fixture",
		Go: buildspec.GoSpec{
			Version: "1.26",
			Module:  "example.com/generated/subpackage-fixture",
		},
		Target: buildspec.TargetSpec{
			Kind:    "cobra",
			Import:  "github.com/acme/cobra-host/cmd/app/root",
			Version: "v0.8.0",
			Root:    "NewRootCommand",
			Output:  "dist/subpackage-fixture",
		},
		Packages: []buildspec.PackageSpec{
			{ID: "provider", Import: "github.com/acme/widgets/pkg/xgoja/testprovider", Version: "v1.2.3", Register: "Register", Replace: "../widgets"},
			{ID: "provider2", Import: "github.com/acme/other/pkg/xgoja", Version: "v2.0.0", Register: "Register", Replace: "../other"},
		},
		Runtimes: map[string]buildspec.RuntimeSpec{
			"repl": {Modules: []buildspec.ModuleInstanceSpec{{Package: "provider", Name: "hello", As: "hello"}}},
		},
		Commands: buildspec.CommandsSpec{Eval: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "eval"}},
	}
	got := RenderGoMod(buildSpec, Options{XGojaModuleVersion: "v0.1.0"})
	for _, want := range []string{
		"github.com/acme/cobra-host v0.8.0",
		"github.com/acme/widgets v1.2.3",
		"github.com/acme/other v2.0.0",
		"replace github.com/acme/widgets => ../widgets",
		"replace github.com/acme/other => ../other",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected go.mod to contain %q, got:\n%s", want, got)
		}
	}
	for _, notWant := range []string{
		"github.com/acme/cobra-host/cmd/app/root v0.8.0",
		"github.com/acme/widgets/pkg/xgoja/testprovider v1.2.3",
		"github.com/acme/other/pkg/xgoja v2.0.0",
		"replace github.com/acme/widgets/pkg/xgoja/testprovider => ../widgets",
		"replace github.com/acme/other/pkg/xgoja => ../other",
	} {
		if strings.Contains(got, notWant) {
			t.Fatalf("go.mod should use module roots, but contained %q:\n%s", notWant, got)
		}
	}
}

func TestRenderMainRegistersProviders(t *testing.T) {
	got := RenderMain(fixtureSpec())
	for _, want := range []string{
		"// Code generated by xgoja; DO NOT EDIT.",
		"providerapi.NewRegistry()",
		"core.Register(registry)",
		"web.Register(registry)",
		"const embeddedSpecJSON = `",
		"app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON})",
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecStableShape(t *testing.T) {
	got := RenderEmbeddedSpec(fixtureSpec())
	for _, want := range []string{
		`"name": "fixture"`,
		`"kind": "xgoja"`,
		`"package": "web"`,
		`"as": "fetch"`,
		`"runtime": "repl"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded runtime spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecIncludesRuntimeAppSettings(t *testing.T) {
	buildSpec := fixtureSpec()
	buildSpec.AppName = "my-app"
	buildSpec.EnvPrefix = "MY_APP"
	buildSpec.ConfigFile = &buildspec.ConfigFileSpec{Enabled: true, Layers: []string{"cwd", "explicit"}, FileName: "config.yaml"}

	var embedded app.RuntimeSpec
	if err := json.Unmarshal([]byte(RenderEmbeddedSpec(buildSpec)), &embedded); err != nil {
		t.Fatalf("unmarshal embedded runtime spec: %v", err)
	}
	if embedded.AppName != "my-app" {
		t.Fatalf("appName = %q", embedded.AppName)
	}
	if embedded.EnvPrefix != "MY_APP" {
		t.Fatalf("envPrefix = %q", embedded.EnvPrefix)
	}
	if embedded.ConfigFile == nil || !embedded.ConfigFile.Enabled {
		t.Fatalf("embedded config missing or disabled: %#v", embedded.ConfigFile)
	}
	if got, want := strings.Join(embedded.ConfigFile.Layers, ","), "cwd,explicit"; got != want {
		t.Fatalf("config layers = %q, want %q", got, want)
	}
	if embedded.ConfigFile.FileName != "config.yaml" {
		t.Fatalf("config fileName = %q", embedded.ConfigFile.FileName)
	}
}

func TestRenderMainIncludesEmbeddedVerbFS(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{{ID: "local", Path: "verbs", Embed: true}}
	got := RenderMain(buildSpec)
	for _, want := range []string{
		`"embed"`,
		`//go:embed xgoja_embed/jsverbs/*`,
		`var embeddedJSVerbs embed.FS`,
		`EmbeddedJSVerbs: embeddedJSVerbs`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
	embeddedSpec := RenderEmbeddedSpec(buildSpec)
	if !strings.Contains(embeddedSpec, `"path": "xgoja_embed/jsverbs/local"`) {
		t.Fatalf("expected embedded runtime spec to rewrite local embedded path, got:\n%s", embeddedSpec)
	}
}

func TestRenderMainIncludesEmbeddedHelpFS(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Help.Sources = []buildspec.HelpSourceSpec{{ID: "local-docs", Path: "docs/help", Embed: true}}
	got := RenderMain(buildSpec)
	for _, want := range []string{
		`"embed"`,
		`//go:embed xgoja_embed/help/*`,
		`var embeddedHelp embed.FS`,
		`EmbeddedHelp: embeddedHelp`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
	for _, notWant := range []string{
		`var embeddedJSVerbs embed.FS`,
		`EmbeddedJSVerbs: embeddedJSVerbs`,
	} {
		if strings.Contains(got, notWant) {
			t.Fatalf("main.go should not contain %q for help-only embed:\n%s", notWant, got)
		}
	}
	embeddedSpec := RenderEmbeddedSpec(buildSpec)
	if !strings.Contains(embeddedSpec, `"path": "xgoja_embed/help/local_docs"`) {
		t.Fatalf("expected embedded runtime spec to rewrite local help path, got:\n%s", embeddedSpec)
	}
}

func TestRenderMainIncludesEmbeddedVerbAndHelpFS(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{{ID: "local-verbs", Path: "verbs", Embed: true}}
	buildSpec.Help.Sources = []buildspec.HelpSourceSpec{{ID: "local-docs", Path: "docs/help", Embed: true}}
	got := RenderMain(buildSpec)
	for _, want := range []string{
		`var embeddedJSVerbs embed.FS`,
		`var embeddedHelp embed.FS`,
		`EmbeddedJSVerbs: embeddedJSVerbs`,
		`EmbeddedHelp: embeddedHelp`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderMainIncludesEmbeddedAssetFS(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Assets = []buildspec.AssetSourceSpec{{ID: "app-assets", Path: "assets", Embed: true}}
	got := RenderMain(buildSpec)
	for _, want := range []string{
		`"embed"`,
		`//go:embed all:xgoja_embed/assets/*`,
		`var embeddedAssets embed.FS`,
		`EmbeddedAssets: embeddedAssets`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected main.go to contain %q, got:\n%s", want, got)
		}
	}
	for _, notWant := range []string{
		`var embeddedJSVerbs embed.FS`,
		`var embeddedHelp embed.FS`,
	} {
		if strings.Contains(got, notWant) {
			t.Fatalf("main.go should not contain %q for asset-only embed:\n%s", notWant, got)
		}
	}
	embeddedSpec := RenderEmbeddedSpec(buildSpec)
	if !strings.Contains(embeddedSpec, `"path": "xgoja_embed/assets/app_assets"`) {
		t.Fatalf("expected embedded runtime spec to rewrite local asset path, got:\n%s", embeddedSpec)
	}
}

func TestRenderEmbeddedSpecAvoidsEmbeddedVerbRootCollisions(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{
		{ID: "local-dev", Path: "verbs-a", Embed: true},
		{ID: "local_dev", Path: "verbs-b", Embed: true},
	}
	got := RenderEmbeddedSpec(buildSpec)
	for _, want := range []string{
		`"path": "xgoja_embed/jsverbs/local_dev"`,
		`"path": "xgoja_embed/jsverbs/local_dev_2"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded runtime spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecAvoidsEmbeddedHelpRootCollisions(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Help.Sources = []buildspec.HelpSourceSpec{
		{ID: "local-docs", Path: "docs-a", Embed: true},
		{ID: "local_docs", Path: "docs-b", Embed: true},
	}
	got := RenderEmbeddedSpec(buildSpec)
	for _, want := range []string{
		`"path": "xgoja_embed/help/local_docs"`,
		`"path": "xgoja_embed/help/local_docs_2"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded runtime spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderEmbeddedSpecAvoidsEmbeddedAssetRootCollisions(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Assets = []buildspec.AssetSourceSpec{
		{ID: "app-assets", Path: "assets-a", Embed: true},
		{ID: "app_assets", Path: "assets-b", Embed: true},
	}
	got := RenderEmbeddedSpec(buildSpec)
	for _, want := range []string{
		`"path": "xgoja_embed/assets/app_assets"`,
		`"path": "xgoja_embed/assets/app_assets_2"`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected embedded runtime spec to contain %q, got:\n%s", want, got)
		}
	}
}

func TestWriteAllCopiesEmbeddedVerbSourcesToCollisionFreeRoots(t *testing.T) {
	baseDir := t.TempDir()
	for _, dir := range []string{"verbs-a", "verbs-b"} {
		verbsDir := filepath.Join(baseDir, dir)
		if err := os.MkdirAll(verbsDir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
		if err := os.WriteFile(filepath.Join(verbsDir, "tools.js"), []byte(`__package__({ name: "tools" })`), 0o644); err != nil {
			t.Fatalf("write %s verb: %v", dir, err)
		}
	}
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.BaseDir = baseDir
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{
		{ID: "local-dev", Path: "verbs-a", Embed: true},
		{ID: "local_dev", Path: "verbs-b", Embed: true},
	}
	dir := t.TempDir()
	if err := WriteAll(dir, buildSpec, Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, path := range []string{
		filepath.Join(dir, "xgoja_embed", "jsverbs", "local_dev", "tools.js"),
		filepath.Join(dir, "xgoja_embed", "jsverbs", "local_dev_2", "tools.js"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected collision-free embedded verb copy %s: %v", path, err)
		}
	}
}

func TestWriteAllCopiesEmbeddedAssetsToCollisionFreeRoots(t *testing.T) {
	baseDir := t.TempDir()
	for _, dir := range []string{"assets-a", "assets-b"} {
		assetDir := filepath.Join(baseDir, dir, "config")
		if err := os.MkdirAll(assetDir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
		if err := os.WriteFile(filepath.Join(assetDir, "default.json"), []byte(`{"ok":true}`), 0o644); err != nil {
			t.Fatalf("write %s asset: %v", dir, err)
		}
	}
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.BaseDir = baseDir
	buildSpec.Assets = []buildspec.AssetSourceSpec{
		{ID: "app-assets", Path: "assets-a", Embed: true},
		{ID: "app_assets", Path: "assets-b", Embed: true},
	}
	dir := t.TempDir()
	if err := WriteAll(dir, buildSpec, Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, path := range []string{
		filepath.Join(dir, "xgoja_embed", "assets", "app_assets", "config", "default.json"),
		filepath.Join(dir, "xgoja_embed", "assets", "app_assets_2", "config", "default.json"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected collision-free embedded asset copy %s: %v", path, err)
		}
	}
}

func TestWriteAllCopiesEmbeddedHelpSourcesToCollisionFreeRoots(t *testing.T) {
	baseDir := t.TempDir()
	for _, dir := range []string{"docs-a", "docs-b"} {
		helpDir := filepath.Join(baseDir, dir, "topics")
		if err := os.MkdirAll(helpDir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", dir, err)
		}
		if err := os.WriteFile(filepath.Join(helpDir, "01-intro.md"), []byte("---\nTitle: Intro\nSlug: intro\n---\n"), 0o644); err != nil {
			t.Fatalf("write %s help: %v", dir, err)
		}
	}
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.BaseDir = baseDir
	buildSpec.Help.Sources = []buildspec.HelpSourceSpec{
		{ID: "local-docs", Path: "docs-a", Embed: true},
		{ID: "local_docs", Path: "docs-b", Embed: true},
	}
	dir := t.TempDir()
	if err := WriteAll(dir, buildSpec, Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, path := range []string{
		filepath.Join(dir, "xgoja_embed", "help", "local_docs", "topics", "01-intro.md"),
		filepath.Join(dir, "xgoja_embed", "help", "local_docs_2", "topics", "01-intro.md"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected collision-free embedded help copy %s: %v", path, err)
		}
	}
}

func TestWriteAll(t *testing.T) {
	dir := t.TempDir()
	if err := WriteAll(dir, fixtureSpec(), Options{XGojaModuleVersion: "v0.1.0"}); err != nil {
		t.Fatalf("write all: %v", err)
	}
	for _, name := range []string{"go.mod", "main.go", "xgoja.gen.json"} {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read generated %s: %v", name, err)
		}
		if len(data) == 0 {
			t.Fatalf("generated %s is empty", name)
		}
	}
}

func TestGeneratedProgramRunsFixtureProvider(t *testing.T) {
	runGeneratedEval(t, buildableSpec("xgoja", "", ""))
}

func TestGeneratedProgramUsesConfiguredReplCommandName(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Commands.Eval.Name = "runjs"
	_, out := runGeneratedCommandWithOutput(t, buildSpec, "runjs", `require("hello").greet("intern")`)
	if strings.TrimSpace(string(out)) != "hello intern" {
		t.Fatalf("configured eval output = %q", out)
	}
}

func TestGeneratedProgramRunsProviderVerbSource(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{{ID: "provider", Package: "fixture", Source: "verbs"}}
	runGeneratedCommand(t, buildSpec, "verbs", "tools", "provider-greet", "--name", "intern")
}

func TestGeneratedProgramRunsProviderVerbWithOwnerBindings(t *testing.T) {
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.Runtimes["repl"] = buildspec.RuntimeSpec{Modules: []buildspec.ModuleInstanceSpec{
		{Package: "fixture", Name: "hello", As: "hello"},
		{Package: "fixture", Name: "owner-check", As: "owner-check"},
	}}
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{{ID: "provider", Package: "fixture", Source: "verbs"}}
	_, out := runGeneratedCommandWithOutput(t, buildSpec, "verbs", "tools", "owner-ping")
	if strings.TrimSpace(string(out)) != "pong" {
		t.Fatalf("owner-ping output = %q", out)
	}
}

func TestGeneratedProgramRunsEmbeddedVerbSource(t *testing.T) {
	baseDir := t.TempDir()
	verbsDir := filepath.Join(baseDir, "verbs")
	if err := os.MkdirAll(verbsDir, 0o755); err != nil {
		t.Fatalf("mkdir verbs: %v", err)
	}
	if err := os.WriteFile(filepath.Join(verbsDir, "tools.js"), []byte(`
__package__({ name: "tools" })
__verb__("embeddedGreet", {
  name: "embedded-greet",
  output: "text",
  fields: {
    name: { type: "string", required: true }
  }
})
function embeddedGreet(name) {
  const hello = require("hello")
  return hello.greet(name)
}
`), 0o644); err != nil {
		t.Fatalf("write verb: %v", err)
	}
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.BaseDir = baseDir
	buildSpec.Commands.JSVerbs = buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "verbs"}
	buildSpec.JSVerbs = []buildspec.JSVerbSourceSpec{{ID: "local", Path: "verbs", Embed: true}}
	dir := runGeneratedCommand(t, buildSpec, "verbs", "tools", "embedded-greet", "--name", "intern")
	if _, err := os.Stat(filepath.Join(dir, "xgoja_embed", "jsverbs", "local", "tools.js")); err != nil {
		t.Fatalf("embedded verb was not copied: %v", err)
	}
}

func TestGeneratedProgramReadsEmbeddedAssetsThroughFSAliases(t *testing.T) {
	baseDir := t.TempDir()
	assetDir := filepath.Join(baseDir, "assets", "config")
	wellKnownDir := filepath.Join(baseDir, "assets", ".well-known")
	if err := os.MkdirAll(assetDir, 0o755); err != nil {
		t.Fatalf("mkdir assets: %v", err)
	}
	if err := os.MkdirAll(wellKnownDir, 0o755); err != nil {
		t.Fatalf("mkdir well-known assets: %v", err)
	}
	if err := os.WriteFile(filepath.Join(assetDir, "default.json"), []byte(`{"ok":true}`), 0o644); err != nil {
		t.Fatalf("write asset: %v", err)
	}
	if err := os.WriteFile(filepath.Join(wellKnownDir, "security.txt"), []byte(`Contact: mailto:security@example.com`), 0o644); err != nil {
		t.Fatalf("write dot asset: %v", err)
	}
	outPath := filepath.ToSlash(filepath.Join(baseDir, "out.json"))
	buildSpec := &buildspec.BuildSpec{
		Name:    "embedded-assets",
		Go:      buildspec.GoSpec{Version: "1.26", Module: "example.com/generated/embedded-assets"},
		Target:  buildspec.TargetSpec{Kind: "xgoja", Output: "dist/embedded-assets"},
		BaseDir: baseDir,
		Packages: []buildspec.PackageSpec{{
			ID:       "go-go-goja-host",
			Import:   "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host",
			Register: "Register",
		}},
		Assets: []buildspec.AssetSourceSpec{{ID: "app-assets", Path: "assets", Embed: true}},
		Runtimes: map[string]buildspec.RuntimeSpec{
			"main": {Modules: []buildspec.ModuleInstanceSpec{
				{
					Package: "go-go-goja-host",
					Name:    "fs",
					As:      "fs:assets",
					Config: map[string]any{
						"embedded": map[string]any{
							"allow":  true,
							"mounts": []any{map[string]any{"asset": "app-assets", "mount": "/app"}},
						},
					},
				},
				{Package: "go-go-goja-host", Name: "fs", As: "fs:host", Config: map[string]any{"allow": true}},
			}},
		},
		Commands: buildspec.CommandsSpec{Eval: buildspec.CommandSpec{Enabled: true, Runtime: "main", Name: "eval"}},
	}
	js := `
		const assets = require("fs:assets");
		const host = require("fs:host");
		let plain = "";
		try { require("fs"); } catch (e) { plain = "missing"; }
		const text = assets.readFileSync("/app/config/default.json", "utf8");
		const wellKnown = assets.readFileSync("/app/.well-known/security.txt", "utf8");
		host.writeFileSync(` + strconv.Quote(outPath) + `, text, "utf8");
		JSON.stringify({ text, wellKnown, plain, wrote: host.existsSync(` + strconv.Quote(outPath) + `) });
	`
	dir, out := runGeneratedCommandWithOutput(t, buildSpec, "eval", js)
	state := string(out)
	for _, want := range []string{`"text":"{\"ok\":true}"`, `"wellKnown":"Contact: mailto:security@example.com"`, `"plain":"missing"`, `"wrote":true`} {
		if !strings.Contains(state, want) {
			t.Fatalf("embedded asset eval output missing %s: %s", want, state)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "xgoja_embed", "assets", "app_assets", "config", "default.json")); err != nil {
		t.Fatalf("embedded asset was not copied: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "xgoja_embed", "assets", "app_assets", ".well-known", "security.txt")); err != nil {
		t.Fatalf("embedded dot-directory asset was not copied: %v", err)
	}
	written, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read host output: %v", err)
	}
	if string(written) != `{"ok":true}` {
		t.Fatalf("host output = %q", written)
	}
}

func TestGeneratedProgramLoadsEmbeddedHelpSource(t *testing.T) {
	baseDir := t.TempDir()
	helpDir := filepath.Join(baseDir, "docs", "help", "topics")
	if err := os.MkdirAll(helpDir, 0o755); err != nil {
		t.Fatalf("mkdir help: %v", err)
	}
	if err := os.WriteFile(filepath.Join(helpDir, "01-local.md"), []byte(`---
Title: Local API
Slug: local-api
Short: Local docs.
IsTopLevel: true
IsTemplate: false
ShowPerDefault: true
SectionType: GeneralTopic
---

Local body.
`), 0o644); err != nil {
		t.Fatalf("write help: %v", err)
	}
	buildSpec := buildableSpec("xgoja", "", "")
	buildSpec.BaseDir = baseDir
	buildSpec.Help.Sources = []buildspec.HelpSourceSpec{{ID: "local", Path: "docs/help", Embed: true}}
	dir, out := runGeneratedCommandWithOutput(t, buildSpec, "help", "local-api")
	if !strings.Contains(string(out), "Local API") || !strings.Contains(string(out), "Local body") {
		t.Fatalf("expected generated help output, got %q", out)
	}
	if _, err := os.Stat(filepath.Join(dir, "xgoja_embed", "help", "local", "topics", "01-local.md")); err != nil {
		t.Fatalf("embedded help was not copied: %v", err)
	}
}

func TestGeneratedCobraTargetAttachesCommands(t *testing.T) {
	buildSpec := buildableSpec("cobra", "github.com/go-go-golems/go-go-goja/pkg/xgoja/testcobra", "NewRootCommand")
	runGeneratedEval(t, buildSpec)
	runGeneratedFixtureCommand(t, buildSpec, "testcobra fixture")
}

func TestGeneratedAdapterTargetUsesAdapterBuild(t *testing.T) {
	buildSpec := buildableSpec("adapter", "github.com/go-go-golems/go-go-goja/pkg/xgoja/testadapter", "")
	runGeneratedEval(t, buildSpec)
	runGeneratedFixtureCommand(t, buildSpec, "testadapter fixture")
}

func runGeneratedEval(t *testing.T, buildSpec *buildspec.BuildSpec) {
	t.Helper()
	dir, out := runGeneratedCommandWithOutput(t, buildSpec, "eval", `require("hello").greet("intern")`)
	_ = dir
	if strings.TrimSpace(string(out)) != "hello intern" {
		t.Fatalf("generated output = %q", out)
	}
}

func runGeneratedFixtureCommand(t *testing.T, buildSpec *buildspec.BuildSpec, want string) {
	t.Helper()
	_, out := runGeneratedCommandWithOutput(t, buildSpec, "fixture")
	if strings.TrimSpace(string(out)) != want {
		t.Fatalf("generated fixture output = %q, want %q", out, want)
	}
}

func runGeneratedCommand(t *testing.T, buildSpec *buildspec.BuildSpec, args ...string) string {
	t.Helper()
	dir, _ := runGeneratedCommandWithOutput(t, buildSpec, args...)
	return dir
}

func runGeneratedCommandWithOutput(t *testing.T, buildSpec *buildspec.BuildSpec, args ...string) (string, []byte) {
	t.Helper()
	repoRoot, err := filepath.Abs("../../../..")
	if err != nil {
		t.Fatalf("repo root: %v", err)
	}
	dir := t.TempDir()
	if err := WriteAll(dir, buildSpec, Options{XGojaModuleVersion: "v0.0.0", XGojaReplace: repoRoot}); err != nil {
		t.Fatalf("write generated program: %v", err)
	}
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy: %v\n%s", err, out)
	}
	cmd = exec.Command("go", append([]string{"run", "."}, args...)...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go run generated program: %v\n%s", err, out)
	}
	return dir, out
}

func buildableSpec(kind, targetImport, root string) *buildspec.BuildSpec {
	return &buildspec.BuildSpec{
		Name:   "fixture",
		Go:     buildspec.GoSpec{Version: "1.26", Module: "example.com/generated/fixture"},
		Target: buildspec.TargetSpec{Kind: kind, Import: targetImport, Root: root, Output: "dist/fixture"},
		Packages: []buildspec.PackageSpec{
			{ID: "fixture", Import: "github.com/go-go-golems/go-go-goja/pkg/xgoja/testprovider", Register: "Register"},
		},
		Runtimes: map[string]buildspec.RuntimeSpec{
			"repl": {Modules: []buildspec.ModuleInstanceSpec{{Package: "fixture", Name: "hello", As: "hello"}}},
		},
		Commands: buildspec.CommandsSpec{Eval: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "eval"}},
	}
}

func fixtureSpec() *buildspec.BuildSpec {
	return &buildspec.BuildSpec{
		Name: "fixture",
		Go: buildspec.GoSpec{
			Version: "1.26",
			Module:  "example.com/generated/fixture",
		},
		Target: buildspec.TargetSpec{Kind: "xgoja", Output: "dist/fixture"},
		Packages: []buildspec.PackageSpec{
			{ID: "core", Import: "github.com/go-go-golems/go-go-goja/xgoja", Register: "Register"},
			{ID: "web", Import: "github.com/go-go-golems/web-stuff/xgoja", Version: "v0.3.0", Register: "Register", Replace: "../web-stuff"},
		},
		Runtimes: map[string]buildspec.RuntimeSpec{
			"repl": {Modules: []buildspec.ModuleInstanceSpec{{Package: "web", Name: "fetch", As: "fetch"}}},
		},
		Commands: buildspec.CommandsSpec{Eval: buildspec.CommandSpec{Enabled: true, Runtime: "repl", Name: "eval"}},
	}
}
