package generate

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/go-go-golems/go-go-goja/cmd/xgoja/internal/buildspec"
)

func RenderMain(spec *buildspec.Spec) string {
	aliases := importAliases(spec.Packages)
	hasEmbedded := hasEmbeddedJSVerbSources(spec)
	var b strings.Builder
	b.WriteString("// Code generated by xgoja; DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	if spec.Target.Kind == "adapter" {
		b.WriteString("\t\"context\"\n")
	}
	if hasEmbedded {
		b.WriteString("\t\"embed\"\n")
	}
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n\n")
	b.WriteString("\t\"github.com/go-go-golems/go-go-goja/pkg/xgoja/app\"\n")
	b.WriteString("\t\"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi\"\n")
	if spec.Target.Kind == "adapter" || spec.Target.Kind == "cobra" {
		fmt.Fprintf(&b, "\ttarget \"%s\"\n", spec.Target.Import)
	}
	for _, pkg := range spec.Packages {
		fmt.Fprintf(&b, "\t%s \"%s\"\n", aliases[pkg.ID], pkg.Import)
	}
	b.WriteString(")\n\n")
	b.WriteString("const embeddedSpecJSON = `")
	b.WriteString(escapeRawString(RenderEmbeddedSpec(spec)))
	b.WriteString("`\n\n")
	if hasEmbedded {
		b.WriteString("//go:embed xgoja_embed/jsverbs/*\n")
		b.WriteString("var embeddedJSVerbs embed.FS\n\n")
	}
	b.WriteString("func main() {\n")
	b.WriteString("\tregistry := providerapi.NewRegistry()\n")
	for _, pkg := range spec.Packages {
		fmt.Fprintf(&b, "\tmust(%s.%s(registry))\n", aliases[pkg.ID], pkg.Register)
	}
	switch spec.Target.Kind {
	case "adapter":
		b.WriteString("\tspec := decodeSpec()\n")
		writeHostConstruction(&b, hasEmbedded)
		b.WriteString("\troot, err := target.Build(context.Background(), host)\n")
		b.WriteString("\tmust(err)\n")
	case "cobra":
		rootFn := strings.TrimSpace(spec.Target.Root)
		if rootFn == "" {
			rootFn = "NewRootCommand"
		}
		b.WriteString("\tspec := decodeSpec()\n")
		writeHostConstruction(&b, hasEmbedded)
		fmt.Fprintf(&b, "\troot := target.%s()\n", rootFn)
		b.WriteString("\thost.AttachDefaultCommands(root)\n")
	default:
		if hasEmbedded {
			b.WriteString("\troot, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON, EmbeddedJSVerbs: embeddedJSVerbs})\n")
		} else {
			b.WriteString("\troot, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON})\n")
		}
		b.WriteString("\tmust(err)\n")
	}
	b.WriteString("\tif err := root.Execute(); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func decodeSpec() *app.Spec {\n")
	b.WriteString("\tspec := &app.Spec{}\n")
	b.WriteString("\tmust(json.Unmarshal([]byte(embeddedSpecJSON), spec))\n")
	b.WriteString("\treturn spec\n")
	b.WriteString("}\n\n")
	b.WriteString("func must(err error) {\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}

func writeHostConstruction(b *strings.Builder, hasEmbedded bool) {
	if hasEmbedded {
		b.WriteString("\thost := app.NewHostWithOptions(registry, spec, app.HostOptions{EmbeddedJSVerbs: embeddedJSVerbs})\n")
		return
	}
	b.WriteString("\thost := app.NewHost(registry, spec)\n")
}

func RenderEmbeddedSpec(spec *buildspec.Spec) string {
	spec = runtimeSpec(spec)
	payload := struct {
		Name     string                       `json:"name"`
		Target   buildspec.TargetSpec         `json:"target"`
		Packages []buildspec.PackageSpec      `json:"packages"`
		Runtimes map[string]buildspec.Runtime `json:"runtimes"`
		Commands buildspec.CommandsSpec       `json:"commands"`
		JSVerbs  []buildspec.JSVerbSourceSpec `json:"jsverbs,omitempty"`
	}{
		Name:     spec.Name,
		Target:   spec.Target,
		Packages: spec.Packages,
		Runtimes: spec.Runtimes,
		Commands: spec.Commands,
		JSVerbs:  spec.JSVerbs,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		panic(err)
	}
	return string(data) + "\n"
}

func runtimeSpec(spec *buildspec.Spec) *buildspec.Spec {
	if spec == nil {
		return nil
	}
	clone := *spec
	if len(spec.JSVerbs) > 0 {
		clone.JSVerbs = append([]buildspec.JSVerbSourceSpec(nil), spec.JSVerbs...)
		for i := range clone.JSVerbs {
			if clone.JSVerbs[i].Embed && clone.JSVerbs[i].Path != "" && clone.JSVerbs[i].Package == "" && clone.JSVerbs[i].Source == "" {
				clone.JSVerbs[i].Path = embeddedJSVerbRoot(clone.JSVerbs[i].ID)
			}
		}
	}
	return &clone
}

func hasEmbeddedJSVerbSources(spec *buildspec.Spec) bool {
	if spec == nil {
		return false
	}
	for _, source := range spec.JSVerbs {
		if source.Embed && source.Path != "" && source.Package == "" && source.Source == "" {
			return true
		}
	}
	return false
}

func embeddedJSVerbRoot(id string) string {
	name := sanitizeIdentifier(id)
	if name == "" {
		name = "source"
	}
	return "xgoja_embed/jsverbs/" + name
}

func importAliases(packages []buildspec.PackageSpec) map[string]string {
	aliases := map[string]string{}
	used := map[string]struct{}{}
	for _, pkg := range packages {
		base := sanitizeIdentifier(pkg.ID)
		if base == "" {
			parts := strings.Split(strings.Trim(pkg.Import, "/"), "/")
			base = sanitizeIdentifier(parts[len(parts)-1])
		}
		if base == "" {
			base = "provider"
		}
		alias := base
		for i := 2; ; i++ {
			if _, ok := used[alias]; !ok {
				break
			}
			alias = fmt.Sprintf("%s%d", base, i)
		}
		used[alias] = struct{}{}
		aliases[pkg.ID] = alias
	}
	return aliases
}

func sortedRuntimeNames(runtimes map[string]buildspec.Runtime) []string {
	names := make([]string, 0, len(runtimes))
	for name := range runtimes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sanitizeIdentifier(value string) string {
	value = strings.TrimSpace(value)
	var b strings.Builder
	for i, r := range value {
		valid := r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || i > 0 && r >= '0' && r <= '9'
		if valid {
			b.WriteRune(r)
			continue
		}
		if b.Len() > 0 {
			b.WriteRune('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return ""
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "provider_" + out
	}
	return out
}

func escapeRawString(value string) string {
	return strings.ReplaceAll(value, "`", "` + \"`\" + `")
}
