package render_test

import (
	"strings"
	"testing"

	"github.com/go-go-golems/go-go-goja/pkg/tsgen/render"
	"github.com/go-go-golems/go-go-goja/pkg/tsgen/spec"
)

func TestRenderBundleDeterministic(t *testing.T) {
	t.Parallel()

	bundle := &spec.Bundle{
		Modules: []*spec.Module{
			{
				Name: "fs",
				Functions: []spec.Function{
					{
						Name: "writeFileSync",
						Params: []spec.Param{
							{Name: "path", Type: spec.String()},
							{Name: "data", Type: spec.Union(spec.String(), spec.Array(spec.Number()))},
						},
						Returns: spec.Void(),
					},
					{
						Name: "readFileSync",
						Params: []spec.Param{
							{Name: "path", Type: spec.String()},
						},
						Returns: spec.String(),
					},
				},
			},
			{
				Name: "exec",
				Functions: []spec.Function{
					{
						Name: "run",
						Params: []spec.Param{
							{Name: "cmd", Type: spec.String()},
							{Name: "args", Type: spec.String(), Variadic: true},
						},
						Returns: spec.String(),
					},
				},
			},
		},
	}

	out, err := render.Bundle(bundle)
	if err != nil {
		t.Fatalf("render bundle: %v", err)
	}

	expected := strings.TrimSpace(`// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT.

declare module "exec" {
  export function run(cmd: string, ...args: string[]): string;
}

declare module "fs" {
  export function readFileSync(path: string): string;
  export function writeFileSync(path: string, data: string | number[]): void;
}`)

	if strings.TrimSpace(out) != expected {
		t.Fatalf("unexpected render output\nexpected:\n%s\n\ngot:\n%s", expected, strings.TrimSpace(out))
	}
}

func TestRenderBundleErrorsOnInvalidTypes(t *testing.T) {
	t.Parallel()

	bundle := &spec.Bundle{
		Modules: []*spec.Module{
			{
				Name: "broken",
				Functions: []spec.Function{
					{Name: "oops", Returns: spec.Named("  ")},
				},
			},
		},
	}

	if _, err := render.Bundle(bundle); err == nil {
		t.Fatalf("expected error, got nil")
	}
}
