package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/go-go-golems/go-go-goja/pkg/tsgen/spec"
)

const defaultHeaderComment = "// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT."

// Bundle renders a descriptor bundle into a deterministic `.d.ts` string.
func Bundle(bundle *spec.Bundle) (string, error) {
	if bundle == nil {
		return "", fmt.Errorf("bundle is nil")
	}

	var sb strings.Builder
	header := strings.TrimSpace(bundle.HeaderComment)
	if header == "" {
		header = defaultHeaderComment
	}
	sb.WriteString(header)
	sb.WriteString("\n\n")

	modules := append([]*spec.Module(nil), bundle.Modules...)
	sort.Slice(modules, func(i, j int) bool {
		return strings.TrimSpace(modules[i].Name) < strings.TrimSpace(modules[j].Name)
	})

	for i, module := range modules {
		if module == nil {
			return "", fmt.Errorf("module at index %d is nil", i)
		}
		block, err := renderModule(module)
		if err != nil {
			return "", err
		}
		sb.WriteString(block)
		if i < len(modules)-1 {
			sb.WriteString("\n\n")
		}
	}

	return sb.String(), nil
}

func renderModule(module *spec.Module) (string, error) {
	moduleName := strings.TrimSpace(module.Name)
	if moduleName == "" {
		return "", fmt.Errorf("module name is empty")
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("declare module %q {\n", moduleName))

	functions := append([]spec.Function(nil), module.Functions...)
	sort.Slice(functions, func(i, j int) bool {
		return strings.TrimSpace(functions[i].Name) < strings.TrimSpace(functions[j].Name)
	})

	for _, fn := range functions {
		line, err := renderFunction(fn)
		if err != nil {
			return "", fmt.Errorf("module %q: %w", moduleName, err)
		}
		sb.WriteString("  ")
		sb.WriteString(line)
		sb.WriteString("\n")
	}

	for _, line := range module.RawDTS {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		sb.WriteString("  ")
		sb.WriteString(trimmed)
		sb.WriteString("\n")
	}

	sb.WriteString("}")
	return sb.String(), nil
}

func renderFunction(fn spec.Function) (string, error) {
	name := strings.TrimSpace(fn.Name)
	if name == "" {
		return "", fmt.Errorf("function name is empty")
	}

	paramParts := make([]string, 0, len(fn.Params))
	for _, param := range fn.Params {
		part, err := renderParam(param)
		if err != nil {
			return "", fmt.Errorf("function %q: %w", name, err)
		}
		paramParts = append(paramParts, part)
	}

	ret, err := renderTypeRef(fn.Returns)
	if err != nil {
		return "", fmt.Errorf("function %q return: %w", name, err)
	}

	return fmt.Sprintf("export function %s(%s): %s;", name, strings.Join(paramParts, ", "), ret), nil
}

func renderParam(param spec.Param) (string, error) {
	name := strings.TrimSpace(param.Name)
	if name == "" {
		return "", fmt.Errorf("param name is empty")
	}

	typ, err := renderTypeRef(param.Type)
	if err != nil {
		return "", fmt.Errorf("param %q: %w", name, err)
	}

	if param.Variadic {
		if param.Type.Kind != spec.TypeKindArray {
			typ += "[]"
		}
		return fmt.Sprintf("...%s: %s", name, typ), nil
	}

	if param.Optional {
		return fmt.Sprintf("%s?: %s", name, typ), nil
	}
	return fmt.Sprintf("%s: %s", name, typ), nil
}

func renderTypeRef(ref spec.TypeRef) (string, error) {
	switch ref.Kind {
	case spec.TypeKindString:
		return "string", nil
	case spec.TypeKindNumber:
		return "number", nil
	case spec.TypeKindBoolean:
		return "boolean", nil
	case spec.TypeKindAny:
		return "any", nil
	case spec.TypeKindUnknown:
		return "unknown", nil
	case spec.TypeKindVoid:
		return "void", nil
	case spec.TypeKindNever:
		return "never", nil

	case spec.TypeKindNamed:
		name := strings.TrimSpace(ref.Name)
		if name == "" {
			return "", fmt.Errorf("named type is empty")
		}
		return name, nil

	case spec.TypeKindArray:
		if ref.Item == nil {
			return "", fmt.Errorf("array item is nil")
		}
		item, err := renderTypeRef(*ref.Item)
		if err != nil {
			return "", err
		}
		if ref.Item.Kind == spec.TypeKindUnion {
			return "(" + item + ")[]", nil
		}
		return item + "[]", nil

	case spec.TypeKindUnion:
		if len(ref.Union) == 0 {
			return "", fmt.Errorf("union has no members")
		}
		out := make([]string, 0, len(ref.Union))
		for i := range ref.Union {
			item, err := renderTypeRef(ref.Union[i])
			if err != nil {
				return "", err
			}
			out = append(out, item)
		}
		return strings.Join(out, " | "), nil

	case spec.TypeKindObject:
		fields := append([]spec.Field(nil), ref.Fields...)
		sort.Slice(fields, func(i, j int) bool {
			return strings.TrimSpace(fields[i].Name) < strings.TrimSpace(fields[j].Name)
		})
		parts := make([]string, 0, len(fields))
		for i, field := range fields {
			name := strings.TrimSpace(field.Name)
			if name == "" {
				return "", fmt.Errorf("object field[%d] name is empty", i)
			}
			fieldType, err := renderTypeRef(field.Type)
			if err != nil {
				return "", fmt.Errorf("object field %q: %w", name, err)
			}
			if field.Optional {
				parts = append(parts, fmt.Sprintf("%s?: %s", name, fieldType))
				continue
			}
			parts = append(parts, fmt.Sprintf("%s: %s", name, fieldType))
		}
		return "{ " + strings.Join(parts, "; ") + " }", nil
	}

	return "", fmt.Errorf("unknown type kind %q", ref.Kind)
}
