// Code generated by logcopter-gen; DO NOT EDIT.

package audit

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.pkg.gojahttp.auth.audit")
