// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT.

declare module "express" {
  export function app(): App;
  export function user(): UserAuthBuilder;
  export function resource(type: string): ResourceBuilder;
  export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "ALL" | string;
  export interface App {
  route(method: HttpMethod, pattern: string): RouteNeedsSecurity;
  get(pattern: string): RouteNeedsSecurity;
  post(pattern: string): RouteNeedsSecurity;
  put(pattern: string): RouteNeedsSecurity;
  patch(pattern: string): RouteNeedsSecurity;
  delete(pattern: string): RouteNeedsSecurity;
  all(pattern: string): RouteNeedsSecurity;
  static(prefix: string, directory: string): void;
  staticFromAssetsModule(prefix: string, assetsModule: unknown, root: string): void;
  spaFromAssetsModule(prefix: string, assetsModule: unknown, root: string, options?: { index?: string; excludePrefixes?: string[] }): void;
  }
  export interface RouteNeedsSecurity {
  name(name: string): RouteNeedsSecurity;
  public(): RouteNeedsHandler;
  auth(spec: UserAuthSpec): RouteNeedsPolicy;
  }
  export interface RouteNeedsPolicy {
  resource(spec: ResourceSpec): RouteNeedsPolicy;
  csrf(required?: boolean): RouteNeedsPolicy;
  audit(event: string): RouteNeedsPolicy;
  allow(action: string): RouteNeedsHandler;
  }
  export interface RouteNeedsHandler {
  csrf(required?: boolean): RouteNeedsHandler;
  audit(event: string): RouteNeedsHandler;
  handle(handler: PlannedHandler): void;
  }
  export interface UserAuthBuilder {
  required(): UserAuthSpec;
  mfaFresh(duration: string): UserAuthSpec;
  }
  export type UserAuthSpec = UserAuthBuilder;
  export interface ResourceBuilder {
  named(name: string): ResourceSpec;
  idFromParam(param: string): ResourceSpec;
  fromParam(param: string): ResourceSpec;
  tenantFromParam(param: string): ResourceSpec;
  withinTenantParam(param: string): ResourceSpec;
  mustExist(): ResourceSpec;
  }
  export type ResourceSpec = ResourceBuilder;
  export type PlannedHandler = (ctx: PlannedContext, res: Response) => unknown;
  export interface PlannedContext {
  request: Request;
  actor: Actor | null;
  body: unknown;
  params: Record<string, string>;
  resources: Record<string, ResourceRef>;
  resource(name: string): ResourceRef | null;
  action: string;
  routeName: string;
  }
  export interface Actor { id: string; kind: string; tenantIds?: string[]; claims?: Record<string, unknown>; }
  export interface ResourceRef { name: string; type: string; id: string; tenantId?: string; claims?: Record<string, unknown>; }
  export interface Request {
  method: string;
  url: string;
  path: string;
  query: Record<string, string | string[]>;
  params: Record<string, string>;
  headers: Record<string, string>;
  cookies: Record<string, string>;
  session: Session | null;
  ip: string;
  body: unknown;
  rawBody: string;
  }
  export interface Session { id: string; isNew: boolean; cookieName: string; }
  export interface Response {
  status(code: number): Response;
  set(name: string, value: string): Response;
  type(value: string): Response;
  json(value: unknown): void;
  send(value?: unknown): void;
  html(value: unknown): void;
  redirect(url: string): void;
  redirect(status: number, url: string): void;
  end(): void;
  }
}
