// Code generated by go-go-goja/cmd/gen-dts. DO NOT EDIT.

declare module "express" {
  export function app(): App;
  export interface App {
  get(pattern: string, handler: Handler): void;
  post(pattern: string, handler: Handler): void;
  put(pattern: string, handler: Handler): void;
  patch(pattern: string, handler: Handler): void;
  delete(pattern: string, handler: Handler): void;
  all(pattern: string, handler: Handler): void;
  mount(prefix: string, handler: MountableHandler, options?: MountOptions): void;
  mountHandler(prefix: string, handler: MountableHandler, options?: MountOptions): void;
  static(prefix: string, directory: string): void;
  staticFromAssetsModule(prefix: string, assetsModule: unknown, root: string): void;
  }
  export interface MountableHandler {}
  export interface MountOptions { stripPrefix?: boolean; excludePrefixes?: string[]; }
  export type Handler = (req: Request, res: Response) => unknown;
  export interface Request {
  method: string;
  url: string;
  path: string;
  query: Record<string, string | string[]>;
  params: Record<string, string>;
  headers: Record<string, string>;
  cookies: Record<string, string>;
  session: Session | null;
  ip: string;
  body: unknown;
  rawBody: string;
  }
  export interface Session { id: string; isNew: boolean; cookieName: string; }
  export interface Response {
  status(code: number): Response;
  set(name: string, value: string): Response;
  type(value: string): Response;
  json(value: unknown): void;
  send(value?: unknown): void;
  html(value: unknown): void;
  redirect(url: string): void;
  redirect(status: number, url: string): void;
  end(): void;
  }
}
