// Code generated by logcopter-gen; DO NOT EDIT.

package replapiv1

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-go-goja.pkg.replapi.pb.proto.goja.replapi.v1")
